/*
 *
 * Chart constants
 *
 */

export const DEFAULT_ACTION = 'app/Chart/DEFAULT_ACTION';

export const OPEN_NEW_ACCOUNT_DIALOG = 'app/Chart/OPEN_NEW_ACCOUNT_DIALOG';
export const CLOSE_NEW_ACCOUNT_DIALOG = 'app/Chart/CLOSE_NEW_ACCOUNT_DIALOG';

export const EDIT_OPEN_ACCOUNT_DIALOG = 'app/Chart/EDIT_OPEN_ACCOUNT_DIALOG';
export const EDIT_CLOSE_ACCOUNT_DIALOG = 'app/Chart/EDIT_CLOSE_ACCOUNT_DIALOG';

export const GET_ALL_ACCOUNT_TYPES = 'app/Chart/GET_ALL_ACCOUNT_TYPES';
export const GET_ALL_ACCOUNT_TYPES_SUCCESS = 'app/Chart/GET_ALL_ACCOUNT_TYPES_SUCCESS';
export const GET_ALL_ACCOUNT_TYPES_ERR = 'app/Chart/GET_ALL_ACCOUNT_TYPES_ERR';

export const GET_PARENT_ACCOUNT_TYPES = 'app/Chart/GET_PARENT_ACCOUNT_TYPES';
export const GET_PARENT_ACCOUNT_TYPES_SUCCESS = 'app/Chart/GET_PARENT_ACCOUNT_TYPES_SUCCESS';
export const GET_PARENT_ACCOUNT_TYPES_ERR = 'app/Chart/GET_PARENT_ACCOUNT_TYPES_ERR';

export const CREATE_NEW_CHART_OF_ACCOUNT = 'app/Chart/CREATE_NEW_CHART_OF_ACCOUNT';
export const CREATE_NEW_CHART_OF_ACCOUNT_SUCCESS = 'app/Chart/CREATE_NEW_CHART_OF_ACCOUNT_SUCCESS';
export const CREATE_NEW_CHART_OF_ACCOUNT_ERR = 'app/Chart/CREATE_NEW_CHART_OF_ACCOUNT_ERR';

export const GET_ALL_CHART_OF_ACCOUNT = 'app/Chart/GET_ALL_CHART_OF_ACCOUNT';
export const GET_ALL_CHART_OF_ACCOUNT_SUCCESS = 'app/Chart/GET_ALL_CHART_OF_ACCOUNT_SUCCESS';
export const GET_ALL_CHART_OF_ACCOUNT_ERR = 'app/Chart/GET_ALL_CHART_OF_ACCOUNT_ERR';

export const DELETE_CHART_OF_ACCOUNT = 'app/Chart/DELETE_CHART_OF_ACCOUNT';
export const DELETE_CHART_OF_ACCOUNT_SUCCESS = 'app/Chart/DELETE_CHART_OF_ACCOUNT_SUCCESS';
export const DELETE_CHART_OF_ACCOUNT_ERR = 'app/Chart/DELETE_CHART_OF_ACCOUNT_ERR';

export const UPDATE_CHART_OF_ACCOUNT = 'app/Chart/UPDATE_CHART_OF_ACCOUNT';
export const UPDATE_CHART_OF_ACCOUNT_SUCCESS = 'app/Chart/UPDATE_CHART_OF_ACCOUNT_SUCCESS';
export const UPDATE_CHART_OF_ACCOUNT_ERR = 'app/Chart/UPDATE_CHART_OF_ACCOUNT_ERR';
