/*
 *
 * LMS Virtual Classroom constants
 *
 */

export const OPEN_NEW_CLASSROOM_DIALOG = 'app/LMS/OPEN_NEW_CLASSROOM_DIALOG';
export const CLOSE_NEW_CLASSROOM_DIALOG = 'app/LMS/CLOSE_NEW_CLASSROOM_DIALOG';

export const OPEN_EDIT_CLASSROOM_DIALOG = 'app/LMS/OPEN_EDIT_CLASSROOM_DIALOG';
export const CLOSE_EDIT_CLASSROOM_DIALOG = 'app/LMS/CLOSE_EDIT_CLASSROOM_DIALOG';

export const CREATE_CLASSROOM = 'app/LMS/CREATE_CLASSROOM';
export const CREATE_CLASSROOM_SUCCESS = 'app/LMS/CREATE_CLASSROOM_SUCCESS';
export const CREATE_CLASSROOM_ERROR = 'app/LMS/CREATE_CLASSROOM_ERROR';

export const UPDATE_CLASSROOM = 'app/LMS/UPDATE_CLASSROOM';
export const UPDATE_CLASSROOM_SUCCESS = 'app/LMS/UPDATE_CLASSROOM_SUCCESS';
export const UPDATE_CLASSROOM_ERROR = 'app/LMS/UPDATE_CLASSROOM_ERROR';

export const GET_CLASSROOMS = 'app/LMS/GET_CLASSROOMS';
export const GET_CLASSROOMS_SUCCESS = 'app/LMS/GET_CLASSROOMS_SUCCESS';
export const GET_CLASSROOMS_ERROR = 'app/LMS/GET_CLASSROOMS_ERROR';
