/*
 *
 * Course Management constants
 *
 */

export const OPEN_NEW_CONTENT_DIALOG = 'app/LMS/OPEN_NEW_CONTENT_DIALOG';
export const CLOSE_NEW_CONTENT_DIALOG = 'app/LMS/CLOSE_NEW_CONTENT_DIALOG';

export const OPEN_EDIT_CONTENT_DIALOG = 'app/LMS/OPEN_EDIT_CONTENT_DIALOG';
export const CLOSE_EDIT_CONTENT_DIALOG = 'app/LMS/CLOSE_EDIT_CONTENT_DIALOG';

export const GET_CONTENTS = 'app/LMS/GET_CONTENTS';
export const GET_CONTENTS_SUCCESS = 'app/LMS/GET_CONTENTS_SUCCESS';
export const GET_CONTENTS_ERROR = 'app/LMS/GET_CONTENTS_ERROR';

export const CREATE_CONTENT = 'app/LMS/CREATE_CONTENT';
export const CREATE_CONTENT_SUCCESS = 'app/LMS/CREATE_CONTENT_SUCCESS';
export const CREATE_CONTENT_ERROR = 'app/LMS/CREATE_CONTENT_ERROR';

export const UPDATE_CONTENT = 'app/LMS/UPDATE_CONTENT';
export const UPDATE_CONTENT_SUCCESS = 'app/LMS/UPDATE_CONTENT_SUCCESS';
export const UPDATE_CONTENT_ERROR = 'app/LMS/UPDATE_CONTENT_ERROR';
