export const SET_START_DATE = 'app/Reports/SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';

export const GET_GENERAL_JOURNALS = 'app/Reports/GET_GENERAL_JOURNALS';
export const GET_GENERAL_JOURNALS_SUCCESS =
  'app/Reports/GET_GENERAL_JOURNALS_SUCCESS';
export const GET_GENERAL_JOURNALS_ERR = 'app/Reports/GET_GENERAL_JOURNALS_ERR';

/** Charts of account */
export const GET_CHART_OF_ACCOUNTS = 'app/Reports/GET_CHART_OF_ACCOUNTS';
export const GET_CHART_OF_ACCOUNTS_SUCCESS =
  'app/Reports/GET_CHART_OF_ACCOUNTS_SUCCESS';
export const GET_CHART_OF_ACCOUNTS_ERR =
  'app/Reports/GET_CHART_OF_ACCOUNTS_ERR';

/** General Ledger */
export const GET_GENERAL_LEDGERS = 'app/Reports/GET_GENERAL_LEDGERS';
export const GET_GENERAL_LEDGERS_SUCCESS =
  'app/Reports/GET_GENERAL_LEDGERS_SUCCESS';
export const GET_GENERAL_LEDGERS_ERR =
  'app/Reports/GET_ALL_GENERAL_LEDGERS_ERR';

/** Trial Balance */
export const GET_ALL_TRIAL_BALANCE = 'app/Reports/GET_ALL_TRIAL_BALANCE';
export const GET_ALL_TRIAL_BALANCE_SUCCESS =
  'app/Reports/GET_ALL_TRIAL_BALANCE_SUCCESS';
export const GET_ALL_TRIAL_BALANCE_ERR =
  'app/Reports/GET_ALL_TRIAL_BALANCE_ERR';

/** Fixed Asset Register */
export const GET_FIXED_ASSET_REGISTER =
  'app/Reports/GET_ALL_FIXED_ASSET_REGISTER';

export const GET_FIXED_ASSET_REGISTER_SUCCESS =
  'app/Reports/GET_ALL_FIXED_ASSET_REGISTER_SUCCESS';

export const GET_FIXED_ASSET_REGISTER_ERR =
  'app/Reports/GET_ALL_FIXED_ASSET_REGISTER_ERR';

export const GET_FIXED_ASSET_REGISTER_RANGE =
  'app/Reports/GET_ALL_FIXED_ASSET_REGISTER_RANGE';

/** Fixed asset schedule */
export const GET_FIXED_ASSET_SCHEDULE =
  'app/Reports/GET_ALL_FIXED_ASSET_SCHEDULE';

export const GET_FIXED_ASSET_SCHEDULE_SUCCESS =
  'app/Reports/GET_ALL_FIXED_ASSET_SCHEDULE_SUCCESS';

export const GET_FIXED_ASSET_SCHEDULE_ERR =
  'app/Reports/GET_ALL_FIXED_ASSET_SCHEDULE_ERR';

export const GET_FIXED_ASSET_SCHEDULE_RANGE =
  'app/Reports/GET_ALL_FIXED_ASSET_SCHEDULE_RANGE';

/** Income statement */
export const GET_ALL_INCOME_STATEMENT_TYPES =
  'app/Reports/GET_ALL_INCOME_STATEMENT_TYPES';

export const GET_INCOME_STATEMENT_SUCCES_ACTION =
  'app/Reports/GET_ALL_INCOME_STATEMENT_SUCCES_ACTION';

export const GET_INCOME_STATEMENT_ERR =
  'app/Reports/GET_ALL_INCOME_STATEMENT_ERR';

export const GET_INCOME_STATEMENT_RANGE =
  'app/Reports/GET_ALL_INCOME_STATEMENT_RANGE';

/** Cash flow */
export const GET_CASH_FLOW = 'app/Reports/GET_ALL_CASH_FLOW';

export const GET_CASH_FLOW_SUCCESS = 'app/Reports/GET_ALL_CASH_FLOW_SUCCESS';

export const GET_CASH_FLOW_ERR = 'app/Reports/GET_ALL_CASH_FLOW_ERR';

/**Financial Position*/
export const GET_FINANCIAL_POSITION =
  'app/Reports/GET_ALL_FINANCIAL_POSITION_TYPES';

export const GET_FINANCIAL_POSITION_SUCCESS =
  'app/Reports/GET_ALL_FINANCIAL_POSITION_SUCCESS';

export const GET_FINANCIAL_POSITION_ERR =
  'app/Reports/GET_ALL_FINANCIAL_POSITION_ERR';

/**Cash Account Register*/
export const GET_CASH_ACCOUNT_REGISTER =
  'app/Reports/GET_ALL_CASH_ACCOUNT_REGISTER';

export const GET_CASH_ACCOUNT_REGISTER_SUCCESS =
  'app/Reports/GET_ALL_CASH_ACCOUNT_REGISTER_SUCCESS';

export const GET_CASH_ACCOUNT_REGISTER_ERR =
  'app/Reports/GET_ALL_CASH_ACCOUNT_REGISTER_ERR';
