/*
 *
 * Budget constants
 *
 */

export const DEFAULT_ACTION = 'app/Budget/DEFAULT_ACTION';


export const OPEN_NEW_BUDGETING_DIALOG = 'app/Budget/OPEN_NEW_BUDGETING_DIALOG';
export const CLOSE_NEW_BUDGETING_DIALOG = 'app/Budget/CLOSE_NEW_BUDGETING_DIALOG';

export const EDIT_OPEN_BUDGETING_DIALOG = 'app/Budget/EDIT_OPEN_BUDGETING_DIALOG';
export const EDIT_CLOSE_BUDGETING_DIALOG = 'app/Budget/EDIT_CLOSE_BUDGETING_DIALOG';

export const CREATE_BUDGETING = 'app/Budget/CREATE_BUDGETING';
export const CREATE_BUDGETING_SUCCESS = 'app/Budget/CREATE_BUDGETING_SUCCESS';
export const CREATE_BUDGETING_ERR = 'app/Budget/CREATE_BUDGETING_ERR';

export const GET_ALL_ACCOUNTING_PERIOD = 'app/Budget/GET_ALL_ACCOUNTING_PERIOD';
export const GET_ALL_ACCOUNTING_PERIOD_SUCCESS = 'app/Budget/GET_ALL_ACCOUNTING_PERIOD_SUCCESS';
export const GET_ALL_ACCOUNTING_PERIOD_ERR = 'app/Budget/GET_ALL_ACCOUNTING_PERIOD_ERR';
