/*
 *
 * Banking constants
 *
 */

export const DEFAULT_ACTION = 'app/Banking/DEFAULT_ACTION';


export const OPEN_NEW_BUDGETING_DIALOG = 'app/Banking/OPEN_NEW_BUDGETING_DIALOG';
export const CLOSE_NEW_BUDGETING_DIALOG = 'app/Banking/CLOSE_NEW_BUDGETING_DIALOG';

export const EDIT_OPEN_BUDGETING_DIALOG = 'app/Banking/EDIT_OPEN_BUDGETING_DIALOG';
export const EDIT_CLOSE_BUDGETING_DIALOG = 'app/Banking/EDIT_CLOSE_BUDGETING_DIALOG';

export const CREATE_BUDGETING = 'app/Banking/CREATE_BUDGETING';
export const CREATE_BUDGETING_SUCCESS = 'app/Banking/CREATE_BUDGETING_SUCCESS';
export const CREATE_BUDGETING_ERR = 'app/Banking/CREATE_BUDGETING_ERR';