/*
 *
 * Settings constants
 *
 */

export const DEFAULT_ACTION = 'app/Settings/DEFAULT_ACTION';

export const CREATE_ACCOUNTING_SETUP = 'app/Settings/CREATE_ACCOUNTING_SETUP';
export const CREATE_ACCOUNTING_SETUP_SUCCESS = 'app/Settings/CREATE_ACCOUNTING_SETUP_SUCCESS';
export const CREATE_ACCOUNTING_SETUP_ERR = 'app/Settings/CREATE_ACCOUNTING_SETUP_ERR';

export const GET_ACCOUNTING_SETUP = 'app/Settings/GET_ACCOUNTING_SETUP';
export const GET_ACCOUNTING_SETUP_SUCCESS = 'app/Settings/GET_ACCOUNTING_SETUP_SUCCESS';
export const GET_ACCOUNTING_SETUP_ERR = 'app/Settings/GET_ACCOUNTING_SETUP_ERR';

export const GET_ALL_ACCOUNTING_PERIOD = 'app/Settings/GET_ALL_ACCOUNTING_PERIOD';
export const GET_ALL_ACCOUNTING_PERIOD_SUCCESS = 'app/Settings/GET_ALL_ACCOUNTING_PERIOD_SUCCESS';
export const GET_ALL_ACCOUNTING_PERIOD_ERR = 'app/Settings/GET_ALL_ACCOUNTING_PERIOD_ERR';

export const OPEN_ACCOUNT_PERIOD_DIALOG = 'app/Settings/OPEN_ACCOUNT_PERIOD_DIALOG';
export const CLOSE_ACCOUNT_PERIOD_DIALOG = 'app/Settings/CLOSE_ACCOUNT_PERIOD_DIALOG';

export const EDIT_OPEN_ACCOUNT_PERIOD_DIALOG = 'app/Settings/EDIT_OPEN_ACCOUNT_PERIOD_DIALOG';
export const EDIT_CLOSE_ACCOUNT_PERIOD_DIALOG = 'app/Settings/EDIT_CLOSE_ACCOUNT_PERIOD_DIALOG';

export const CREATE_ACCOUNT_PERIOD = 'app/Settings/CREATE_ACCOUNT_PERIOD';
export const CREATE_ACCOUNT_PERIOD_SUCCESS = 'app/Settings/CREATE_ACCOUNT_PERIOD_SUCCESS';
export const CREATE_ACCOUNT_PERIOD_ERR = 'app/Settings/CREATE_ACCOUNT_PERIOD_ERR';

