/*
 *
 * Settings constants
 *
 */
export const DEFAULT_ACTION = 'app/Settings/DEFAULT_ACTION';

export const CREATE_ACCOUNTING_SETUP = 'app/Settings/CREATE_ACCOUNTING_SETUP';
export const CREATE_ACCOUNTING_SETUP_SUCCESS = 'app/Settings/CREATE_ACCOUNTING_SETUP_SUCCESS';
export const CREATE_ACCOUNTING_SETUP_ERR = 'app/Settings/CREATE_ACCOUNTING_SETUP_ERR';

export const GET_ACCOUNTING_SETUP = 'app/Settings/GET_ACCOUNTING_SETUP';
export const GET_ACCOUNTING_SETUP_SUCCESS = 'app/Settings/GET_ACCOUNTING_SETUP_SUCCESS';
export const GET_ACCOUNTING_SETUP_ERR = 'app/Settings/GET_ACCOUNTING_SETUP_ERR';

export const GET_ALL_ACCOUNTING_PERIOD = 'app/Settings/GET_ALL_ACCOUNTING_PERIOD';
export const GET_ALL_ACCOUNTING_PERIOD_SUCCESS = 'app/Settings/GET_ALL_ACCOUNTING_PERIOD_SUCCESS';
export const GET_ALL_ACCOUNTING_PERIOD_ERR = 'app/Settings/GET_ALL_ACCOUNTING_PERIOD_ERR';

export const GET_BUSINESS_TYPES = 'app/Settings/GET_BUSINESS_TYPES';
export const GET_BUSINESS_TYPES_SUCCESS = 'app/Settings/GET_BUSINESS_TYPES_SUCCESS';
export const GET_BUSINESS_TYPES_ERROR = 'app/Settings/GET_BUSINESS_TYPES_ERROR';

export const GET_DEPRECIATION_AREA = 'app/Settings/GET_DEPRECIATION_AREA';
export const GET_DEPRECIATION_AREA_SUCCESS = 'app/Settings/GET_DEPRECIATION_AREA_SUCCESS';
export const GET_DEPRECIATION_AREA_ERROR = 'app/Settings/GET_DEPRECIATION_AREA_ERROR';

export const GET_CHART_OF_ACCOUNTS = 'app/Settings/GET_CHART_OF_ACCOUNTS';
export const GET_CHART_OF_ACCOUNTS_SUCCESS = 'app/Settings/GET_CHART_OF_ACCOUNTS_SUCCESS';
export const GET_CHART_OF_ACCOUNTS_ERROR = 'app/Settings/GET_CHART_OF_ACCOUNTS_ERROR';

export const GET_DEFAULT_CHART_OF_ACCOUNTS = 'app/Settings/GET_DEFAULT_CHART_OF_ACCOUNTS';
export const GET_DEFAULT_CHART_OF_ACCOUNTS_SUCCESS = 'app/Settings/GET_DEFAULT_CHART_OF_ACCOUNTS_SUCCESS';
export const GET_DEFAULT_CHART_OF_ACCOUNTS_ERROR = 'app/Settings/GET_DEFAULT_CHART_OF_ACCOUNTS_ERROR';

export const GET_CURRENCIES = 'app/Settings/GET_CURRENCIES';
export const GET_CURRENCIES_SUCCESS = 'app/Settings/GET_CURRENCIES_SUCCESS';
export const GET_CURRENCIES_ERROR = 'app/Settings/GET_CURRENCIES_ERROR';

export const OPEN_ACCOUNT_PERIOD_DIALOG = 'app/Settings/OPEN_ACCOUNT_PERIOD_DIALOG';
export const CLOSE_ACCOUNT_PERIOD_DIALOG = 'app/Settings/CLOSE_ACCOUNT_PERIOD_DIALOG';

export const EDIT_OPEN_ACCOUNT_PERIOD_DIALOG = 'app/Settings/EDIT_OPEN_ACCOUNT_PERIOD_DIALOG';
export const EDIT_CLOSE_ACCOUNT_PERIOD_DIALOG = 'app/Settings/EDIT_CLOSE_ACCOUNT_PERIOD_DIALOG';

export const OPEN_DIALOG_CLOSE_ACCOUNT_PERIOD = 'app/Settings/OPEN_DIALOG_CLOSE_ACCOUNT_PERIOD';
export const CLOSE_DIALOG_CLOSE_ACCOUNT_PERIOD = 'app/Settings/CLOSE_DIALOG_CLOSE_ACCOUNT_PERIOD';

export const CREATE_ACCOUNT_PERIOD = 'app/Settings/CREATE_ACCOUNT_PERIOD';
export const CREATE_ACCOUNT_PERIOD_SUCCESS = 'app/Settings/CREATE_ACCOUNT_PERIOD_SUCCESS';
export const CREATE_ACCOUNT_PERIOD_ERR = 'app/Settings/CREATE_ACCOUNT_PERIOD_ERR';

export const UPDATE_ACCOUNT_PERIOD = 'app/Settings/UPDATE_ACCOUNT_PERIOD';
export const UPDATE_ACCOUNT_PERIOD_SUCCESS = 'app/Settings/UPDATE_ACCOUNT_PERIOD_SUCCESS';
export const UPDATE_ACCOUNT_PERIOD_ERR = 'app/Settings/UPDATE_ACCOUNT_PERIOD_ERR';

export const SET_ACCOUNT_PERIOD_AS_ACTIVE = 'app/Settings/SET_ACCOUNT_PERIOD_AS_ACTIVE';
export const SET_ACCOUNT_PERIOD_AS_ACTIVE_SUCCESS = 'app/Settings/SET_ACCOUNT_PERIOD_AS_ACTIVE_SUCCESS';
export const SET_ACCOUNT_PERIOD_AS_ACTIVE_ERR = 'app/Settings/SET_ACCOUNT_PERIOD_AS_ACTIVE_ERR';

