/*
 *
 * Crm Contact Groups constants
 *
 */

export const OPEN_NEW_CONTACT_GROUPS_DIALOG = 'app/Crm/OPEN_NEW_CONTACT_GROUPS_DIALOG';
export const CLOSE_NEW_CONTACT_GROUPS_DIALOG = 'app/Crm/CLOSE_NEW_CONTACT_GROUPS_DIALOG';

export const OPEN_NEW_ASSIGN_CONTACT_DIALOG = 'app/Crm/OPEN_NEW_ASSIGN_CONTACT_DIALOG';
export const CLOSE_NEW_ASSIGN_CONTACT_DIALOG = 'app/Crm/CLOSE_NEW_ASSIGN_CONTACT_DIALOG';
