/*
 *
 * Lms quizzes constants
 *
 */

export const OPEN_NEW_QUIZ_DIALOG = 'app/LMS/OPEN NEW QUIZ DIALOG';
export const CLOSE_NEW_QUIZ_DIALOG = 'app/LMS/CLOSE NEW QUIZ DIALOG';

export const OPEN_EDIT_QUIZ_DIALOG = 'app/LMS/OPEN EDIT QUIZ DIALOG';
export const CLOSE_EDIT_QUIZ_DIALOG = 'app/LMS/CLOSE EDIT QUIZ DIALOG';

export const CREATE_QUIZ = 'app/LMS/CREATE QUIZ';
export const CREATE_QUIZ_SUCCESS = 'app/LMS/CREATE QUIZ SUCCESS';
export const CREATE_QUIZ_ERROR = 'app/LMS/CREATE QUIZ ERROR';

export const UPDATE_QUIZ = 'app/LMS/UPDATE QUIZ';
export const UPDATE_QUIZ_SUCCESS = 'app/LMS/UPDATE QUIZ SUCCESS';
export const UPDATE_QUIZ_ERROR = 'app/LMS/UPDATE QUIZ ERROR';

export const GET_QUIZZES = 'app/LMS/GET QUIZZES';
export const GET_QUIZZES_SUCCESS = 'app/LMS/GET QUIZZES SUCCESS';
export const GET_QUIZZES_ERROR = 'app/LMS/GET QUIZZES ERROR';
