export const GET_APPLICATIONS = 'app/Home/GET_APPLICATIONS';
export const GET_APPLICATIONS_SUCCESS = 'app/Home/GET_APPLICATIONS_SUCCESS';
export const GET_APPLICATIONS_ERROR = 'app/Home/GET_APPLICATIONS_ERROR';

export const GET_APPLICATION = 'app/Home/GET_APPLICATION';
export const GET_APPLICATION_SUCCESS = 'app/Home/GET_APPLICATION_SUCCESS';
export const GET_APPLICATION_ERROR = 'app/Home/GET_APPLICATION_ERROR';
