/*
 *
 * UtilityPage task constants
 *
 */

export const OPEN_NEW_TASK_DIALOG = 'app/UtilityPage/OPEN NEW TASK DIALOG';
export const CLOSE_NEW_TASK_DIALOG = 'app/UtilityPage/CLOSE NEW TASK DIALOG';
export const OPEN_EDIT_TASK_DIALOG = 'app/UtilityPage/OPEN EDIT TASK DIALOG';
export const CLOSE_EDIT_TASK_DIALOG = 'app/UtilityPage/CLOSE EDIT TASK DIALOG';
export const OPEN_ASSIGN_TO_DIALOG = 'app/UtilityPage/OPEN ASSIGN TO DIALOG';
export const CLOSE_ASSIGN_TO_DIALOG = 'app/UtilityPage/CLOSE EDIT TASK DIALOG';
export const OPEN_CONFIRM_TASK_DELETE_DIALOG = 'app/UtilityPage/OPEN CONFIRM_TASK_DELETE DIALOG';
export const CLOSE_CONFIRM_TASK_DELETE_DIALOG = 'app/UtilityPage/CLOSE CONFIRM_TASK_DELETE DIALOG';

export const OPEN_TASK_PREVIEW_DIALOG = 'app/UtilityPage/OPEN_TASK_PREVIEW_DIALOG';
export const CLOSE_TASK_PREVIEW_DIALOG = 'app/UtilityPage/CLOSE_TASK_PREVIEW_DIALOG';

export const ADD_TASK_COMMENT = 'app/UtilityPage/ADD TASK COMMENT';
export const ADD_TASK_COMMENT_SUCCESS = 'app/UtilityPage/ADD TASK COMMENT SUCCESS';
export const ADD_TASK_COMMENT_ERROR = 'app/UtilityPage/ADD TASK COMMENT ERROR';

export const GET_TASK_COMMENTS = 'app/UtilityPage/GET TASK COMMENTS';
export const GET_TASK_COMMENTS_SUCCESS = 'app/UtilityPage/GET TASK COMMENTS SUCCESS';

export const ADD_TASK_ATTACHMENT = 'app/UtilityPage/ADD TASK ATTACHMENT';
export const ADD_TASK_ATTACHMENT_SUCCESS = 'app/UtilityPage/ADD TASK ATTACHMENT SUCCESS';

export const DELETE_TASK = 'app/UtilityPage/DELETE TASK';
export const DELETE_TASK_SUCCESS = 'app/UtilityPage/DELETE TASK SUCCESS';

export const REMOVE_TASK_ATTACHMENT = 'app/UtilityPage/REMOVE TASK ATTACHMENT';
export const REMOVE_TASK_ATTACHMENT_SUCCESS = 'app/UtilityPage/REMOVE TASK ATTACHMENT SUCCESS';

export const GET_UTILITY_TASK = 'app/UtilityPage/GET UTILITY TASK';
export const GET_UTILITY_TASK_SUCCESS = 'app/UtilityPage/GET UTILITY TASK SUCCESS';
export const GET_UTILITY_TASK_ERROR = 'app/UtilityPage/GET UTILITY TASK ERROR';

export const GET_UTILITY_TASKS = 'app/UtilityPage/GET UTILITY TASKS';
export const GET_UTILITY_TASKS_SUCCESS = 'app/UtilityPage/GET ALL UTILITY TASKS SUCCESS';

export const UPDATE_UTILITY_TASK = 'app/UtilityPage/UPDATE UTILITY TASK';
export const UPDATE_UTILITY_TASK_SUCCESS = 'app/UtilityPage/UPDATE UTILITY TASK SUCCESS';

export const GET_UTILITY_TASKS_BY_STATUS = 'app/UtilityPage/GET UTILITY TASKS BY STATUS';
export const GET_UTILITY_TASKS_BY_STATUS_SUCCESS = 'app/UtilityPage/GET ALL UTILITY TASKS BY STATUS SUCCESS';

export const CREATE_UTILITY_TASKS = 'app/UtilityPage/CREATE UTILITY TASKS';
export const CREATE_UTILITY_TASKS_SUCCESS = 'app/UtilityPage/CREATE UTILITY TASKS SUCCESS';
export const CREATE_UTILITY_TASKS_ERROR = 'app/UtilityPage/CREATE UTILITY TASKS ERROR';

export const GET_UTILITY_TASKS_ERROR = 'app/UtilityPage/GET UTILITY TASKS ERROR';
export const GET_ASSIGNEDTO_BY_UUID = 'app/UtilityPage/GET ASSIGNEDTO BY UUID';
export const GET_ASSIGNEDTO_BY_UUID_SUCCESS = 'app/UtilityPage/GET ASSIGNEDTO BY UUID SUCCESS';

export const GET_EMPLOYEES = 'app/UtilityPage/GET EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'app/UtilityPage/GET EMPLOYEES SUCCESS';
export const GET_EMPLOYEES_ERROR = 'app/UtilityPage/GET EMPLOYEES ERROR';

export const GET_USER_BY_UUID = 'app/UtilityPage/GET USER BY UUID';
export const GET_USER_BY_UUID_SUCCESS = 'app/UtilityPage/GET USER BY UUID SUCCESS';
export const GET_USER_BY_UUID_ERROR = 'app/UtilityPage/GET USER BY UUID ERROR';

