export const GET_PAYROLL_SETUP = 'app/Payroll/GET_PAYROLL_SETUP';
export const GET_PAYROLL_SETUP_SUCCESS = 'app/Payroll/GET_PAYROLL_SETUP_SUCCESS';
export const GET_PAYROLL_SETUP_ERROR = 'app/Payroll/GET_PAYROLL_SETUP_ERROR';

// ALLOWANCE DIALOG
export const OPEN_NEW_ALLOWANCE_DIALOG = 'app/Payroll/OPEN_NEW_ALLOWANCE_DIALOG';
export const CLOSE_NEW_ALLOWANCE_DIALOG = 'app/Payroll/CLOSE_NEW_ALLOWANCE_DIALOG';

export const OPEN_EDIT_ALLOWANCE_DIALOG = 'app/Payroll/OPEN_EDIT_ALLOWANCE_DIALOG';
export const CLOSE_EDIT_ALLOWANCE_DIALOG = 'app/Payroll/CLOSE_EDIT_ALLOWANCE_DIALOG';

// BENEFIT DIALOG
export const OPEN_NEW_BENEFIT_DIALOG = 'app/Payroll/OPEN_NEW_BENEFIT_DIALOG';
export const CLOSE_NEW_BENEFIT_DIALOG = 'app/Payroll/CLOSE_NEW_BENEFIT_DIALOG';

export const OPEN_EDIT_BENEFIT_DIALOG = 'app/Payroll/OPEN_EDIT_BENEFIT_DIALOG';
export const CLOSE_EDIT_BENEFIT_DIALOG = 'app/Payroll/CLOSE_EDIT_BENEFIT_DIALOG';

// EARNINGS DIALOG
export const OPEN_NEW_EARNING_DIALOG = 'app/payroll/OPEN_NEW_EARNING_DIALOG';
export const CLOSE_NEW_EARNING_DIALOG = 'app/payroll/CLOSE_NEW_EARNING_DIALOG';

export const OPEN_EDIT_EARNING_DIALOG = 'app/payroll/OPEN_EDIT_EARNING_DIALOG';
export const CLOSE_EDIT_EARNING_DIALOG = 'app/payroll/CLOSE_EDIT_EARNING_DIALOG';

// DEDUCTION DIALOG
export const OPEN_NEW_DEDUCTION_DIALOG = 'app/payroll/OPEN_NEW_DEDUCTION_DIALOG';
export const CLOSE_NEW_DEDUCTION_DIALOG = 'app/payroll/CLOSE_NEW_DEDUCTION_DIALOG';

export const OPEN_EDIT_DEDUCTION_DIALOG = 'app/payroll/OPEN_EDIT_DEDUCTION_DIALOG';
export const CLOSE_EDIT_DEDUCTION_DIALOG = 'app/payroll/CLOSE_EDIT_DEDUCTION_DIALOG';

// ALLOWANCES
export const CREATE_ALLOWANCE = 'app/payroll/CREATE_ALLOWANCE';
export const CREATE_ALLOWANCE_SUCCESS = 'app/Payroll/CREATE_ALLOWANCE_SUCCESS';
export const CREATE_ALLOWANCE_ERROR = 'app/Payroll/CREATE_ALLOWANCE_ERROR';

export const GET_ALLOWANCES = 'app/payroll/GET_ALLOWANCES';
export const GET_ALLOWANCES_SUCCESS = 'app/payroll/GET_ALLOWANCES_SUCCESS';
export const GET_ALLOWANCES_ERROR = 'app/payroll/GET_ALLOWANCES_ERROR';

export const GET_ALLOWANCE_BY_ID = 'app/payroll/GET_ALLOWANCE_BY_ID';
export const GET_ALLOWANCE_BY_ID_SUCCESS = 'app/payroll/GET_ALLOWANCE_BY_ID_SUCCESS';
export const GET_ALLOWANCE_BY_ID_ERROR = 'app/payroll/GET_ALLOWANCE_BY_ID_ERROR';

// BENEFITS
export const CREATE_BENEFIT = 'app/payroll/CREATE_BENEFIT';
export const CREATE_BENEFIT_SUCCESS = 'app/Payroll/CREATE_BENEFIT_SUCCESS';
export const CREATE_BENEFIT_ERROR = 'app/Payroll/CREATE_BENEFIT_ERROR';

export const GET_BENEFITS = 'app/payroll/GET_BENEFITS';
export const GET_BENEFITS_SUCCESS = 'app/payroll/GET_BENEFITS_SUCCESS';
export const GET_BENEFITS_ERROR = 'app/payroll/GET_BENEFITS_ERROR';

export const GET_BENEFIT_BY_ID = 'app/payroll/GET_BENEFIT_BY_ID';
export const GET_BENEFIT_BY_ID_SUCCESS = 'app/payroll/GET_BENEFIT_BY_ID_SUCCESS';
export const GET_BENEFIT_BY_ID_ERROR = 'app/payroll/GET_BENEFIT_BY_ID_ERROR';

// EARNINGS
export const CREATE_EARNING = 'app/payroll/CREATE_EARNING';
export const CREATE_EARNING_SUCCESS = 'app/Payroll/CREATE_EARNING_SUCCESS';
export const CREATE_EARNING_ERROR = 'app/Payroll/CREATE_EARNING_ERROR';

export const GET_EARNINGS = 'app/payroll/GET_EARNINGS';
export const GET_EARNINGS_SUCCESS = 'app/payroll/GET_EARNINGS_SUCCESS';
export const GET_EARNINGS_ERROR = 'app/payroll/GET_EARNINGS_ERROR';

export const GET_EARNING_BY_ID = 'app/payroll/GET_EARNING_BY_ID';
export const GET_EARNING_BY_ID_SUCCESS = 'app/payroll/GET_EARNING_BY_ID_SUCCESS';
export const GET_EARNING_BY_ID_ERROR = 'app/payroll/GET_EARNING_BY_ID_ERROR';

// DEDUCTIONS
export const CREATE_DEDUCTION = 'app/payroll/CREATE_DEDUCTION';
export const CREATE_DEDUCTION_SUCCESS = 'app/Payroll/CREATE_DEDUCTION_SUCCESS';
export const CREATE_DEDUCTION_ERROR = 'app/Payroll/CREATE_DEDUCTION_ERROR';

export const GET_DEDUCTIONS = 'app/payroll/GET_DEDUCTIONS';
export const GET_DEDUCTIONS_SUCCESS = 'app/payroll/GET_DEDUCTIONS_SUCCESS';
export const GET_DEDUCTIONS_ERROR = 'app/payroll/GET_DEDUCTIONS_ERROR';

export const GET_DEDUCTION_BY_ID = 'app/payroll/GET_DEDUCTION_BY_ID';
export const GET_DEDUCTION_BY_ID_SUCCESS = 'app/payroll/GET_DEDUCTION_BY_ID_SUCCESS';
export const GET_DEDUCTION_BY_ID_ERROR = 'app/payroll/GET_DEDUCTION_BY_ID_ERROR';
