/*
 *
 * Campaign constants
 *
 */
export const GET_EMPLOYEES = 'app/Crm/GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'app/Crm/GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'app/Crm/GET_EMPLOYEES_ERROR';

export const GET_FACEBOOK_ACCESS_TOKEN = 'app/Crm/GET_FACEBOOK_ACCESS_TOKEN';
export const GET_FACEBOOK_ACCESS_TOKEN_SUCCESS = 'app/Crm/GET_FACEBOOK_ACCESS_TOKEN_SUCCESS';
export const GET_FACEBOOK_ACCESS_TOKEN_ERROR = 'app/Crm/GET_FACEBOOK_ACCESS_TOKEN_ERROR';

export const GENERATE_FACEBOOK_AUTHORISE_URL = 'app/Crm/GENERATE_FACEBOOK_AUTHORISE_URL';
export const GENERATE_FACEBOOK_AUTHORISE_URL_SUCCESS = 'app/Crm/GENERATE_FACEBOOK_AUTHORISE_URL_SUCCESS';
export const GENERATE_FACEBOOK_AUTHORISE_URL_ERROR = 'app/Crm/GENERATE_FACEBOOK_AUTHORISE_URL_ERROR';

export const GET_USER_DATA = 'app/Crm/GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'app/Crm/GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_ERROR = 'app/Crm/GET_USER_DATA_ERROR';

export const OPEN_NEW_SOCIAL_MEDIA_DIALOG = 'app/Crm/OPEN_NEW_SOCIAL_MEDIA_DIALOG';
export const CLOSE_NEW_SOCIAL_MEDIA_DIALOG = 'app/Crm/CLOSE_NEW_SOCIAL_MEDIA_DIALOG';

export const OPEN_EDIT_SOCIAL_MEDIA_DIALOG = 'app/Crm/OPEN_EDIT_SOCIAL_MEDIA_DIALOG';
export const CLOSE_EDIT_SOCIAL_MEDIA_DIALOG = 'app/Crm/CLOSE_EDIT_SOCIAL_MEDIA_DIALOG';

export const OPEN_SOCIAL_MEDIA_DETAILS_DIALOG = 'app/Crm/OPEN_SOCIAL_MEDIA_DETAILS_DIALOG';
export const CLOSE_SOCIAL_MEDIA_DETAILS_DIALOG = 'app/Crm/CLOSE_SOCIAL_MEDIA_DETAILS_DIALOG';

