/*
 *
 * Campaign constants
 *
 */
export const GET_EMPLOYEES = 'app/Crm/GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'app/Crm/GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'app/Crm/GET_EMPLOYEES_ERROR';

export const GET_CAMPAIGNS = 'app/Crm/GET_CAMPAIGNS';
export const GET_CAMPAIGNS_SUCCESS = 'app/Crm/GET_CAMPAIGNS_SUCCESS';
export const GET_CAMPAIGNS_ERROR = 'app/Crm/GET_CAMPAIGNS_ERROR';

export const CREATE_CAMPAIGN = 'app/Crm/CREATE_NEW_CAMPAIGN';
export const CREATE_CAMPAIGN_SUCCESS = 'app/Crm/CREATE_NEW_CAMPAIGN_SUCCESS';
export const CREATE_CAMPAIGN_ERROR = 'app/Crm/CREATE_NEW_CAMPAIGN_ERROR';

export const UPDATE_CAMPAIGN = 'app/Crm/UPDATE_CAMPAIGN';
export const UPDATE_CAMPAIGN_SUCCESS = 'app/Crm/UPDATE_CAMPAIGN_SUCCESS';
export const UPDATE_CAMPAIGN_ERROR = 'app/Crm/UPDATE_CAMPAIGN_ERROR';

export const OPEN_NEW_CAMPAIGN_DIALOG = 'app/Crm/OPEN_NEW_CAMPAIGN_DIALOG';
export const CLOSE_NEW_CAMPAIGN_DIALOG = 'app/Crm/CLOSE_NEW_CAMPAIGN_DIALOG';

export const OPEN_EDIT_CAMPAIGN_DIALOG = 'app/Crm/OPEN_EDIT_CAMPAIGN_DIALOG';
export const CLOSE_EDIT_CAMPAIGN_DIALOG = 'app/Crm/CLOSE_EDIT_CAMPAIGN_DIALOG';

export const OPEN_CAMPAIGN_DETAILS_DIALOG = 'app/Crm/OPEN_CAMPAIGN_DETAILS_DIALOG';
export const CLOSE_CAMPAIGN_DETAILS_DIALOG = 'app/Crm/CLOSE_CAMPAIGN_DETAILS_DIALOG';

