export const GET_MODULES = 'app/Home/GET_MODULES';
export const GET_MODULES_SUCCESS = 'app/Home/GET_MODULES_SUCCESS';
export const GET_MODULES_ERROR = 'app/Home/GET_MODULES_ERROR';

export const GET_MODULES_BY_ACCESS_OFFERS =
  'app/Home/GET_MODULES_BY_ACCESS_OFFERS';
export const GET_MODULES_BY_ACCESS_OFFERS_SUCCESS =
  'app/Home/GET_MODULES_BY_ACCESS_OFFERS_SUCCESS';
export const GET_MODULES_BY_ACCESS_OFFERS_ERROR =
  'app/Home/GET_MODULES_BY_ACCESS_OFFERS_ERROR';

export const REGISTER_MODULES = 'app/Home/REGISTER_MODULES';
export const REGISTER_MODULES_SUCCESS = 'app/Home/REGISTER_MODULES_SUCCESS';
export const REGISTER_MODULES_ERROR = 'app/Home/REGISTER_MODULES_ERROR';

export const GET_PAYMENT_GATEWAYS = 'app/Home/GET_PAYMENT_GATEWAYS';
export const GET_PAYMENT_GATEWAYS_SUCCESS = 'app/Home/GET_PAYMENT_GATEWAYS_SUCCESS';
export const GET_PAYMENT_GATEWAYS_ERROR = 'app/Home/GET_PAYMENT_GATEWAYS_ERROR';

export const VERIFY_PAYMENT = 'app/Home/VERIFY_PAYMENT';
export const VERIFY_PAYMENT_SUCCESS = 'app/Home/VERIFY_PAYMENT_SUCCESS';
export const VERIFY_PAYMENT_ERROR = 'app/Home/VERIFY_PAYMENT_ERROR';

export const GET_MODULE = 'app/Home/GET_MODULE';
