/*
 *
 * Payrun constants
 *
 */
export const OPEN_NEW_PAYRUN_DIALOG = 'app/Payruns/OPEN_NEW_PAYRUN_DIALOG';
export const CLOSE_NEW_PAYRUN_DIALOG = 'app/Payruns/CLOSE_NEW_PAYRUN_DIALOG';

export const OPEN_EDIT_PAYRUN_DIALOG = 'app/Payruns/OPEN_EDIT_PAYRUN_DIALOG';
export const CLOSE_EDIT_PAYRUN_DIALOG = 'app/Payruns/CLOSE_EDIT_PAYRUN_DIALOG';

export const OPEN_DELETE_PAYRUN_DIALOG = 'app/Payruns/OPEN_DELETE_PAYRUN_DIALOG';
export const CLOSE_DELETE_PAYRUN_DIALOG = 'app/Payruns/CLOSE_DELETE_PAYRUN_DIALOG';

export const OPEN_ACTIVATE_PAYRUN_DIALOG = 'app/Payruns/OPEN_ACTIVATE_PAYRUN_DIALOG';
export const CLOSE_ACTIVATE_PAYRUN_DIALOG = 'app/Payruns/CLOSE_ACTIVATE_PAYRUN_DIALOG';

export const OPEN_DEACTIVATE_PAYRUN_DIALOG = 'app/Payruns/OPEN_DEACTIVATE_PAYRUN_DIALOG';
export const CLOSE_DEACTIVATE_PAYRUN_DIALOG = 'app/Payruns/CLOSE_DEACTIVATE_PAYRUN_DIALOG';

export const CREATE_PAYRUN = 'app/Payruns/CREATE_PAYRUN';
export const CREATE_PAYRUN_SUCCESS = 'app/Payruns/CREATE_PAYRUN_SUCCESS';
export const CREATE_PAYRUN_ERROR = 'app/Payruns/CREATE_PAYRUN_ERROR';

export const GET_PAYRUNS = 'app/Payruns/GET_PAYRUNS';
export const GET_PAYRUNS_SUCCESS = 'app/Payruns/GET_PAYRUNS_SUCCESS';
export const GET_PAYRUNS_ERROR = 'app/Payruns/GET_PAYRUNS_ERROR';

export const GET_PAYRUN_BY_ID = 'app/Payruns/GET_PAYRUN_BY_ID';
export const GET_PAYRUN_BY_ID_SUCCESS = 'app/Payruns/GET_PAYRUN_BY_ID_SUCCESS';
export const GET_PAYRUN_BY_ID_ERROR = 'app/Payruns/GET_PAYRUN_BY_ID_ERROR';

export const UPDATE_PAYRUN = 'app/Payruns/UPDATE_PAYRUN';
export const UPDATE_PAYRUN_SUCCESS = 'app/Payruns/UPDATE_PAYRUN_SUCCESS';
export const UPDATE_PAYRUN_ERROR = 'app/Payruns/UPDATE_PAYRUN_ERROR';

export const ACTIVATE_DEACTIVATE_PAYRUN = 'app/Payruns/ACTIVATE_DEACTIVATE_PAYRUN';
export const ACTIVATE_DEACTIVATE_PAYRUN_SUCCESS = 'app/Payruns/ACTIVATE_DEACTIVATE_PAYRUN_SUCCESS';
export const ACTIVATE_DEACTIVATE_PAYRUN_ERROR = 'app/Payruns/ACTIVATE_DEACTIVATE_PAYRUN_ERROR';

export const DELETE_PAYRUN = 'app/Payruns/DELETE_PAYRUN';
export const DELETE_PAYRUN_SUCCESS = 'app/Payruns/DELETE_PAYRUN_SUCCESS';
export const DELETE_PAYRUN_ERROR = 'app/Payruns/DELETE_PAYRUN_ERROR';
