export const GET_DASHBOARD_STATS = 'app/Dashboard/GET_DASHBOARD_STATS';
export const GET_DASHBOARD_STATS_SUCCESS = 'app/Dashboard/GET_DASHBOARD_STATS_SUCCESS';
export const GET_DASHBOARD_STATS_ERROR = 'app/Dashboard/GET_DASHBOARD_STATS_ERROR';
