/*
 *
 * Crm constants
 *
 */

export const OPEN_NEW_CONTACT_DIALOG = 'app/Crm/OPEN_NEW_CONTACT_DIALOG';
export const CLOSE_NEW_CONTACT_DIALOG = 'app/Crm/CLOSE_NEW_CONTACT_DIALOG';

export const OPEN_EDIT_CONTACT_DIALOG = 'app/Crm/OPEN_EDIT_CONTACT_DIALOG';
export const CLOSE_EDIT_CONTACT_DIALOG = 'app/Crm/CLOSE_EDIT_CONTACT_DIALOG';

export const CREATE_NEW_CONTACT = 'app/Crm/CREATE_NEW_CONTACT';
export const CREATE_NEW_CONTACT_SUCCESS = 'app/Crm/CREATE_NEW_CONTACT_SUCCESS';
export const CREATE_NEW_CONTACT_ERROR = 'app/Crm/CREATE_NEW_CONTACT_ERROR';

export const UPDATE_CONTACT = 'app/Crm/UPDATE_CONTACT';
export const UPDATE_CONTACT_SUCCESS = 'app/Crm/UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_ERROR = 'app/Crm/UPDATE_CONTACT_ERROR';

export const GET_ALL_CONTACTS = 'app/Crm/GET_ALL_CONTACTS';
export const GET_ALL_CONTACTS_SUCCESS = 'app/Crm/GET_ALL_CONTACTS_SUCCESS';
export const GET_ALL_CONTACTS_ERROR = 'app/Crm/GET_ALL_CONTACTS_ERROR';
export const OPEN_NEW_CONTACT_DETAILS_DIALOG = 'app/Crm/OPEN_NEW_CONTACT_DETAILS_DIALOG';
export const CLOSE_NEW_CONTACT_DETAILS_DIALOG = 'app/Crm/CLOSE_NEW_CONTACT_DETAILS_DIALOG';

export const GET_CONTACTS_GROUPS = 'app/Crm/GET CONTACTS GROUPS';
export const GET_CONTACTS_GROUPS_SUCCESS = 'app/Crm/GET CONTACTS GROUPS SUCCESS';
export const GET_CONTACTS_GROUPS_ERROR = 'app/Crm/GET CONTACTS GROUPS ERROR';
