/*
 *
 * Jobs constants
 *
 */

export const OPEN_NEW_JOB_DIALOG = 'app/JOBS/OPEN_NEW_JOB_DIALOG';
export const CLOSE_NEW_JOB_DIALOG = 'app/JOBS/CLOSE_NEW_JOB_DIALOG';

export const OPEN_EDIT_JOB_DIALOG = 'app/JOBS/OPEN_EDIT_JOB_DIALOG';
export const CLOSE_EDIT_JOB_DIALOG = 'app/JOBS/CLOSE_EDIT_JOB_DIALOG';

export const CREATE_JOB = 'app/JOBS/CREATE_JOB';
export const CREATE_JOB_SUCCESS = 'app/JOBS/CREATE_JOB_SUCCESS';
export const CREATE_JOB_ERROR = 'app/JOBS/CREATE_JOB_ERROR';

export const UPDATE_JOB = 'app/JOBS/UPDATE_JOB';
export const UPDATE_JOB_SUCCESS = 'app/JOBS/UPDATE_JOB_SUCCESS';
export const UPDATE_JOB_ERROR = 'app/JOBS/UPDATE_JOB_ERROR';

export const GET_JOBS = 'app/JOBS/GET_JOBS';
export const GET_JOBS_SUCCESS = 'app/JOBS/GET_JOBS_SUCCESS';
export const GET_JOBS_ERROR = 'app/JOBS/GET_JOBS_ERROR';

export const GET_CUSTOMERS = 'app/JOBS/GET_CUSTOMERS';
export const GET_CUSTOMERS_SUCCESS = 'app/JOBS/GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_ERROR = 'app/JOBS/GET_CUSTOMERS_ERROR';

export const GET_EMPLOYEES = 'app/JOBS/GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'app/JOBS/GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'app/JOBS/GET_EMPLOYEES_ERROR';
