/*
 *
 * Campaign constants
 *
 */
export const GET_EMPLOYEES = 'app/Crm/GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'app/Crm/GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'app/Crm/GET_EMPLOYEES_ERROR';

export const GET_SOCIAL_MEDIAS = 'app/Crm/GET_SOCIAL_MEDIAS';
export const GET_SOCIAL_MEDIAS_SUCCESS = 'app/Crm/GET_SOCIAL_MEDIAS_SUCCESS';
export const GET_SOCIAL_MEDIAS_ERROR = 'app/Crm/GET_SOCIAL_MEDIAS_ERROR';

export const CREATE_SOCIAL_MEDIA = 'app/Crm/CREATE_NEW_SOCIAL_MEDIA';
export const CREATE_SOCIAL_MEDIA_SUCCESS = 'app/Crm/CREATE_NEW_SOCIAL_MEDIA_SUCCESS';
export const CREATE_SOCIAL_MEDIA_ERROR = 'app/Crm/CREATE_NEW_SOCIAL_MEDIA_ERROR';

export const UPDATE_SOCIAL_MEDIA = 'app/Crm/UPDATE_SOCIAL_MEDIA';
export const UPDATE_SOCIAL_MEDIA_SUCCESS = 'app/Crm/UPDATE_SOCIAL_MEDIA_SUCCESS';
export const UPDATE_SOCIAL_MEDIA_ERROR = 'app/Crm/UPDATE_SOCIAL_MEDIA_ERROR';

export const OPEN_NEW_SOCIAL_MEDIA_DIALOG = 'app/Crm/OPEN_NEW_SOCIAL_MEDIA_DIALOG';
export const CLOSE_NEW_SOCIAL_MEDIA_DIALOG = 'app/Crm/CLOSE_NEW_SOCIAL_MEDIA_DIALOG';

export const OPEN_EDIT_SOCIAL_MEDIA_DIALOG = 'app/Crm/OPEN_EDIT_SOCIAL_MEDIA_DIALOG';
export const CLOSE_EDIT_SOCIAL_MEDIA_DIALOG = 'app/Crm/CLOSE_EDIT_SOCIAL_MEDIA_DIALOG';

export const OPEN_SOCIAL_MEDIA_DETAILS_DIALOG = 'app/Crm/OPEN_SOCIAL_MEDIA_DETAILS_DIALOG';
export const CLOSE_SOCIAL_MEDIA_DETAILS_DIALOG = 'app/Crm/CLOSE_SOCIAL_MEDIA_DETAILS_DIALOG';

