/*
 *
 * Crm constants
 *
 */
// LEADS DIALOG 
export const OPEN_NEW_LEAD_DIALOG = 'app/Crm/OPEN_NEW_LEAD_DIALOG';
export const CLOSE_NEW_LEAD_DIALOG = 'app/Crm/CLOSE_NEW_LEAD_DIALOG';
export const OPEN_EDIT_LEAD_DIALOG = 'app/Crm/OPEN_EDIT_LEAD_DIALOG';
export const CLOSE_EDIT_LEAD_DIALOG = 'app/Crm/CLOSE_EDIT_LEAD_DIALOG';
// LEAD SOURCES DIALOG
export const OPEN_NEW_LEAD_SOURCE_DIALOG = 'app/Crm/OPEN_NEW_LEAD_SOURCE_DIALOG';
export const CLOSE_NEW_LEAD_SOURCE_DIALOG = 'app/Crm/CLOSE_NEW_LEAD_SOURCE_DIALOG';
export const OPEN_EDIT_LEAD_SOURCE_DIALOG = 'app/Crm/OPEN_EDIT_LEAD_SOURCE_DIALOG';
export const CLOSE_EDIT_LEAD_SOURCE_DIALOG = 'app/Crm/CLOSE_EDIT_LEAD_SOURCE_DIALOG';
// LEAD TAGS DIALOG
export const OPEN_NEW_LEAD_TAG_DIALOG = 'app/Crm/OPEN_NEW_LEAD_TAG_DIALOG';
export const CLOSE_NEW_LEAD_TAG_DIALOG = 'app/Crm/CLOSE_NEW_LEAD_TAG_DIALOG';
export const OPEN_EDIT_LEAD_TAG_DIALOG = 'app/Crm/OPEN_EDIT_LEAD_TAG_DIALOG';
export const CLOSE_EDIT_LEAD_TAG_DIALOG = 'app/Crm/CLOSE_EDIT_LEAD_TAG_DIALOG';
// LEAD STAGES DIALOG
export const OPEN_NEW_LEAD_STAGE_DIALOG = 'app/Crm/OPEN_NEW_LEAD_STAGE_DIALOG';
export const CLOSE_NEW_LEAD_STAGE_DIALOG = 'app/Crm/CLOSE_NEW_LEAD_STAGE_DIALOG';
export const OPEN_EDIT_LEAD_STAGE_DIALOG = 'app/Crm/OPEN_EDIT_LEAD_STAGE_DIALOG';
export const CLOSE_EDIT_LEAD_STAGE_DIALOG = 'app/Crm/CLOSE_EDIT_LEAD_STAGE_DIALOG';

// LEADS
export const CREATE_LEAD = 'app/Crm/CREATE_LEAD';
export const CREATE_LEAD_SUCCESS = 'app/Crm/CREATE_LEAD_SUCCESS';
export const CREATE_LEAD_ERROR = 'app/Crm/CREATE_LEAD_ERROR';

export const UPDATE_LEAD = 'app/Crm/UPDATE_LEAD';
export const UPDATE_LEAD_SUCCESS = 'app/Crm/UPDATE_LEAD_SUCCESS';
export const UPDATE_LEAD_ERROR = 'app/Crm/UPDATE_LEAD_ERROR';

export const GET_LEADS = 'app/Crm/GET_ALL_LEADS';
export const GET_LEADS_SUCCESS = 'app/Crm/GET_ALL_LEADS_SUCCESS';
export const GET_LEADS_ERROR = 'app/Crm/GET_ALL_LEADS_ERROR';

// LEAD SOURCES
export const GET_LEAD_SOURCES = 'app/Crm/GET_LEAD_SOURCES';
export const GET_LEAD_SOURCES_SUCCESS = 'app/Crm/GET_LEAD_SOURCES_SUCCESS';
export const GET_LEAD_SOURCES_ERROR = 'app/Crm/GET_LEAD_SOURCES_ERROR';

export const CREATE_LEAD_SOURCE = 'app/Crm/CREATE LEAD SOURCE';
export const CREATE_LEAD_SOURCE_SUCCESS = 'app/Crm/CREATE LEAD SOURCE SUCCESS';
export const CREATE_LEAD_SOURCE_ERROR = 'app/Crm/CREATE LEAD SOURCE ERROR';

export const UPDATE_LEAD_SOURCE = 'app/Crm/UPDATE_LEAD_SOURCE';
export const UPDATE_LEAD_SOURCE_SUCCESS = 'app/Crm/UPDATE_LEAD_SOURCE_SUCCESS';
export const UPDATE_LEAD_SOURCE_ERROR = 'app/Crm/UPDATE_LEAD_SOURCE_ERROR';
// LEAD TAGS
export const GET_LEAD_TAGS = 'app/Crm/GET_LEAD_TAGS';
export const GET_LEAD_TAGS_SUCCESS = 'app/Crm/GET_LEAD_TAGS_SUCCESS';
export const GET_LEAD_TAGS_ERROR = 'app/Crm/GET_LEAD_TAGS_ERROR';

export const CREATE_LEAD_TAG = 'app/Crm/CREATE_LEAD_TAG';
export const CREATE_LEAD_TAG_SUCCESS = 'app/Crm/CREATE_LEAD_TAG_SUCCESS';
export const CREATE_LEAD_TAG_ERROR = 'app/Crm/CREATE_LEAD_TAG_ERROR';

export const UPDATE_LEAD_TAG = 'app/Crm/UPDATE_LEAD_TAG';
export const UPDATE_LEAD_TAG_SUCCESS = 'app/Crm/UPDATE_LEAD_TAG_SUCCESS';
export const UPDATE_LEAD_TAG_ERROR = 'app/Crm/UPDATE_LEAD_TAG_ERROR';
// LEAD STAGES
export const GET_LEAD_STAGES = 'app/Crm/GET_LEAD_STAGES';
export const GET_LEAD_STAGES_SUCCESS = 'app/Crm/GET_LEAD_STAGES_SUCCESS';
export const GET_LEAD_STAGES_ERROR = 'app/Crm/GET_LEAD_STAGES_ERROR';

export const CREATE_LEAD_STAGE = 'app/Crm/CREATE_LEAD_STAGE';
export const CREATE_LEAD_STAGE_SUCCESS = 'app/Crm/CREATE_LEAD_TAG_SUCCESS';
export const CREATE_LEAD_STAGE_ERROR = 'app/Crm/CREATE_LEAD_TAG_ERROR';

export const UPDATE_LEAD_STAGE = 'app/Crm/UPDATE_LEAD_STAGE';
export const UPDATE_LEAD_STAGE_SUCCESS = 'app/Crm/UPDATE_LEAD_STAGE_SUCCESS';
export const UPDATE_LEAD_STAGE_ERROR = 'app/Crm/UPDATE_LEAD_STAGE_ERROR';

