/*
 *
 * Employee Salary constants
 *
 */

export const OPEN_NEW_EMPLOYEE_SALARY_DIALOG = 'app/EmployeeSalary/OPEN_NEW_EMPLOYEE_SALARY_DIALOG';
export const CLOSE_NEW_EMPLOYEE_SALARY_DIALOG = 'app/EmployeeSalary/CLOSE_NEW_EMPLOYEE_SALARY_DIALOG';

export const OPEN_EDIT_EMPLOYEE_SALARY_DIALOG = 'app/EmployeeSalary/OPEN_EDIT_EMPLOYEE_SALARY_DIALOG';
export const CLOSE_EDIT_EMPLOYEE_SALARY_DIALOG = 'app/EmployeeSalary/CLOSE_EDIT_EMPLOYEE_SALARY_DIALOG';

export const CREATE_EMPLOYEE_SALARY = 'app/EmployeeSalary/CREATE_EMPLOYEE_SALARY';
export const CREATE_EMPLOYEE_SALARY_SUCCESS = 'app/EmployeeSalary/CREATE_EMPLOYEE_SALARY_SUCCESS';
export const CREATE_EMPLOYEE_SALARY_ERROR = 'app/EmployeeSalary/CREATE_EMPLOYEE_SALARY_ERROR';

export const GET_EMPLOYEE_SALARIES = 'app/EmployeeSalary/GET_EMPLOYEE_SALARIES';
export const GET_EMPLOYEE_SALARIES_SUCCESS = 'app/EmployeeSalary/GET_EMPLOYEE_SALARIES_SUCCESS';
export const GET_EMPLOYEE_SALARIES_ERROR = 'app/EmployeeSalary/GET_EMPLOYEE_SALARIES_ERROR';

export const GET_EMPLOYEE_SALARY_BY_ID = 'app/EmployeeSalary/GET_EMPLOYEE_SALARY_BY_ID';
export const GET_EMPLOYEE_SALARY_BY_ID_SUCCESS = 'app/EmployeeSalary/GET_EMPLOYEE_SALARY_BY_ID_SUCCESS';
export const GET_EMPLOYEE_SALARY_BY_ID_ERROR = 'app/EmployeeSalary/GET_EMPLOYEE_SALARY_BY_ID_ERROR';

export const DELETE_EMPLOYEE_SALARY = 'app/EmployeeSalary/DELETE_EMPLOYEE_SALARY';
export const DELETE_EMPLOYEE_SALARY_SUCCESS = 'app/EmployeeSalary/DELETE_EMPLOYEE_SALARY_SUCCESS';
export const DELETE_EMPLOYEE_SALARY_ERROR = 'app/EmployeeSalary/DELETE_EMPLOYEE_SALARY_ERROR';

export const UPDATE_EMPLOYEE_SALARY = 'app/EmployeeSalary/UPDATE_EMPLOYEE_SALARY';
export const UPDATE_EMPLOYEE_SALARY_SUCCESS = 'app/EmployeeSalary/UPDATE_EMPLOYEE_SALARY_SUCCESS';
export const UPDATE_EMPLOYEE_SALARY_ERROR = 'app/EmployeeSalary/UPDATE_EMPLOYEE_SALARY_ERROR';

export const OPEN_DELETE_EMPLOYEE_SALARY_DIALOG = 'app/EmployeeSalary/OPEN_DELETE_EMPLOYEE_SALARY_DIALOG';
export const CLOSE_DELETE_EMPLOYEE_SALARY_DIALOG = 'app/EmployeeSalary/CLOSE_DELETE_EMPLOYEE_SALARY_DIALOG';
