/*
 *
 * Crm constants
 *
 */

export const GET_EMPLOYEES = 'app/Crm/GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'app/Crm/GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'app/Crm/GET_EMPLOYEES_ERROR';

export const GET_CONTACTS = 'app/Crm/GET_CONTACTS';
export const GET_CONTACTS_SUCCESS = 'app/Crm/GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_ERROR = 'app/Crm/GET_CONTACTS_ERROR';

export const GET_SCHEDULES = 'app/Crm/GET_SCHEDULES';
export const GET_SCHEDULES_SUCCESS = 'app/Crm/GET_SCHEDULE_SUCCESS';
export const GET_SCHEDULES_ERROR = 'app/Crm/GET_SCHEDULE_ERROR';

export const CREATE_SCHEDULE = 'app/Crm/CREATE_SCHEDULE';
export const CREATE_SCHEDULE_SUCCESS = 'app/Crm/CREATE_SCHEDULE_SUCCESS';
export const CREATE_SCHEDULE_ERROR = 'app/Crm/CREATE_SCHEDULE_ERROR';

export const OPEN_NEW_SCHEDULE_DIALOG = 'app/Crm/OPEN_NEW_SCHEDULE_DIALOG';
export const CLOSE_NEW_SCHEDULE_DIALOG = 'app/Crm/CLOSE_NEW_SCHEDULE_DIALOG';

export const OPEN_NEW_PARTICIPANT_DIALOG = 'app/Crm/OPEN_NEW_PARTICIPANT_DIALOG';
export const CLOSE_NEW_PARTICIPANT_DIALOG = 'app/Crm/CLOSE_NEW_PARTICIPANT_DIALOG';
