/*
 *
 * ItemPage constants
 *
 */

export const OPEN_NEW_ITEM_DIALOG = 'app/ItemPage/OPEN_NEW_ITEM_DIALOG';
export const CLOSE_NEW_ITEM_DIALOG = 'app/ItemPage/CLOSE_NEW_ITEM_DIALOG';

export const OPEN_VIEW_ITEM_DIALOG = 'app/ItemPage/OPEN_VIEW_ITEM_DIALOG';
export const CLOSE_VIEW_ITEM_DIALOG = 'app/ItemPage/CLOSE_VIEW_ITEM_DIALOG';

export const OPEN_NEW_TRANSFER_ORDER_DIALOG =
  'app/ItemPage/OPEN_NEW_TRANSFER_ORDER_DIALOG';
export const CLOSE_NEW_TRANSFER_ORDER_DIALOG =
  'app/ItemPage/CLOSE_NEW_TRANSFER_ORDER_DIALOG';

export const OPEN_VIEW_TRANSFER_ORDER_DIALOG =
  'app/ItemPage/OPEN_VIEW_TRANSFER_ORDER_DIALOG';
export const CLOSE_VIEW_TRANSFER_ORDER_DIALOG =
  'app/ItemPage/CLOSE_VIEW_TRANSFER_ORDER_DIALOG';

export const GET_ALL_WAREHOUSE = 'app/ItemPage/GET_ALL_WAREHOUSE';
export const GET_ALL_WAREHOUSE_SUCCESS =
  'app/ItemPage/GET_ALL_WAREHOUSE_SUCCESS';
export const GET_ALL_WAREHOUSE_ERROR = 'app/ItemPage/GET_ALL_WAREHOUSE_ERROR';

export const GET_ALL_ITEMS = 'app/ItemPage/GET_ALL_ITEMS';
export const GET_ALL_ITEMS_SUCCESS = 'app/ItemPage/GET_ALL_ITEMS_SUCCESS';
export const GET_ALL_ITEMS_ERROR = 'app/ItemPage/GET_ALL_ITEMS_ERROR';

export const CREATE_NEW_ITEM = 'app/ItemPage/CREATE_NEW_ITEM';
export const CREATE_NEW_ITEM_SUCCESS = 'app/ItemPage/CREATE_NEW_ITEM_SUCCESS';
export const CREATE_NEW_ITEM_ERROR = 'app/ItemPage/CREATE_NEW_ITEM_ERROR';

export const CREATE_NEW_TRANSFER_ORDER =
  'app/ItemPage/CREATE_NEW_TRANSFER_ORDER';
export const CREATE_NEW_TRANSFER_ORDER_SUCCESS =
  'app/ItemPage/CREATE_NEW_TRANSFER_ORDER_SUCCESS';
export const CREATE_NEW_TRANSFER_ORDER_ERROR =
  'app/ItemPage/CREATE_NEW_TRANSFER_ORDER_ERROR';

export const GET_ALL_TRANSFER_ORDER = 'app/ItemPage/GET_ALL_TRANSFER_ORDER';
export const GET_ALL_TRANSFER_ORDER_SUCCESS =
  'app/ItemPage/GET_ALL_TRANSFER_ORDER_SUCCESS';
export const GET_ALL_TRANSFER_ORDER_ERROR =
  'app/ItemPage/GET_ALL_TRANSFER_ORDER_ERROR';

export const OPEN_INVENTORY_ADJUST_DIALOG =
  'app/ItemPage/OPEN_INVENTORY_ADJUST_DIALOG';
export const CLOSE_INVENTORY_ADJUST_DIALOG =
  'app/ItemPage/CLOSE_INVENTORY_ADJUST_DIALOG';

export const CREATE_NEW_INVENTORY_ADJUSTMENT =
  'app/ItemPage/CREATE_NEW_INVENTORY_ADJUSTMENT';
export const CREATE_NEW_INVENTORY_ADJUSTMENT_SUCCESS =
  'app/ItemPage/CREATE_NEW_INVENTORY_ADJUSTMENT_SUCCESS';
export const CREATE_NEW_INVENTORY_ADJUSTMENT_ERROR =
  'app/ItemPage/CREATE_NEW_INVENTORY_ADJUSTMENT_ERROR';

export const GET_ALL_INVENTORY_ADJUSTMENT =
  'app/ItemPage/GET_ALL_INVENTORY_ADJUSTMENT';
export const GET_ALL_INVENTORY_ADJUSTMENT_SUCCESS =
  'app/ItemPage/GET_ALL_INVENTORY_ADJUSTMENT_SUCCESS';
export const GET_ALL_INVENTORY_ADJUSTMENT_ERROR =
  'app/ItemPage/GET_ALL_INVENTORY_ADJUSTMENT_ERROR';

export const GET_ALL_ITEMS_PER_WAREHOUSE =
  'app/ItemPage/GET_ALL_ITEMS_PER_WAREHOUSE';
export const GET_ALL_ITEMS_PER_WAREHOUSE_SUCCESS =
  'app/ItemPage/GET_ALL_ITEMS_PER_WAREHOUSE_SUCCESS';
export const GET_ALL_ITEMS_PER_WAREHOUSE_ERROR =
  'app/ItemPage/GET_ALL_ITEMS_PER_WAREHOUSE_ERROR';

export const GET_ITEM_BY_ID = 'app/ItemPage/GET_ITEM_BY_ID';
export const GET_ITEM_BY_ID_SUCCESS = 'app/ItemPage/GET_ITEM_BY_ID_SUCCESS';
export const GET_ITEM_BY_ID_ERROR = 'app/ItemPage/GET_ITEM_BY_ID_ERROR';

export const GET_STOCK_LOCATIONS = 'app/ItemPage/GET_STOCK_LOCATIONS';
export const GET_STOCK_LOCATIONS_SUCCESS =
  'app/ItemPage/GET_STOCK_LOCATIONS_SUCCESS';
export const GET_STOCK_LOCATIONS_ERROR =
  'app/ItemPage/GET_STOCK_LOCATIONS_ERROR';

export const GET_TRANSFER_ORDER_BY_ID = 'app/ItemPage/GET_TRANSFER_ORDER_BY_ID';
export const GET_TRANSFER_ORDER_BY_ID_SUCCESS =
  'app/ItemPage/GET_TRANSFER_ORDER_BY_ID_SUCCESS';
export const GET_TRANSFER_ORDER_BY_ID_ERROR =
  'app/ItemPage/GET_TRANSFER_ORDER_BY_ID_ERROR';

export const GET_INVENTORY_ADJUST_BY_ID =
  'app/ItemPage/GET_INVENTORY_ADJUST_BY_ID';
export const GET_INVENTORY_ADJUST_BY_ID_SUCCESS =
  'app/ItemPage/GET_INVENTORY_ADJUST_BY_ID_SUCCESS';
export const GET_INVENTORY_ADJUST_BY_ID_ERROR =
  'app/ItemPage/GET_INVENTORY_ADJUST_BY_ID_ERROR';
