const SidebarConfig = [
  {
    module: ['home'],
    menus: [
      { id: 1, name: 'Home', url: '/', icon: 'home' },
      { id: 2, name: 'Admin Panel', url: '/dashboard', icon: 'build' },
    ],
  },
  {
    module: ['utility', 'folders', 'tasks'],
    menus: [
      { id: 1, name: 'Home', url: '/', icon: 'home' },
      { id: 2, name: 'Dashboard', url: '/dashboard', icon: 'build' },
    ],
  },
  {
    module: [
      'dashboard',
      'employees',
      'users',
      'user',
      'organization',
      'work-order',
      'email',
      'profile',
      'roles',
      'settings',
      'user-profile',
    ],
    menus: [
      { id: 1, name: 'Dashboard', url: '/dashboard', icon: 'dashboard' },
      {
        id: 2,
        name: 'Organization',
        url: '/organization',
        icon: 'business_center',
      },
      { id: 3, name: 'Applications', url: '/applications', icon: 'apps' },
      { id: 4, name: 'Employees', url: '/users', icon: 'group' },
      { id: 5, name: 'User Profile', url: '/user-profile', icon: 'person' },
      { id: 6, name: 'Roles', url: '/roles', icon: 'person', disabled: true },
      {
        id: 7,
        name: 'Security',
        url: '/security',
        icon: 'security',
        disabled: true,
      },
      { id: 8, name: 'Settings', url: '/settings/email', icon: 'settings' },
    ],
  },
  {
    module: ['hr', 'human-resource'],
    menus: [
      { id: 1, name: 'Dashboard', url: '/hr/dashboard', icon: 'dashboard' },
      {
        id: 2,
        name: 'Organization',
        url: '/hr/employees',
        icon: 'business_center',
      },
      {
        id: 3,
        name: 'Recruitment',
        url: '/hr/recruitment',
        icon: 'find_in_page',
      },
      {
        id: 4,
        name: 'Attendance',
        url: '/human-resource/attendance',
        icon: 'person',
      },
      {
        id: 6,
        name: 'Announcements',
        url: '/hr/announcement',
        icon: 'announcement',
      },
      {
        id: 7,
        name: 'Performance',
        url: '/human-resource/performance/goals',
        icon: 'thumb_up',
      },
      {
        id: 7,
        name: 'Leave Management',
        url: '/human-resource/leave-management/leave-request',
        icon: 'single_bed',
      },
    ],
  },
  {
    module: ['payroll'],
    menus: [
      {
        id: 1,
        name: 'Dashboard',
        url: '/payroll/dashboard',
        icon: 'dashboard',
      },
      {
        id: 2,
        name: 'Employee Salary',
        url: '/payroll/employee-salary',
        icon: 'business_center',
      },
      {
        id: 3,
        name: 'Pay Runs',
        url: '/payroll/pay-runs',
        icon: 'find_in_page',
      },
      {
        id: 4,
        name: 'Payroll Items',
        url: '/payroll/payroll-items',
        icon: 'person',
      },
      {
        id: 5,
        name: 'Salary Advance',
        url: '/payroll/salary-advance',
        icon: 'announcement',
      },
      { id: 6, name: 'Reports', url: '/payroll/reports', icon: 'thumb_up' },
      {
        id: 7,
        name: 'Settings',
        url: '#',
        icon: 'single_bed',
        submenus: [
          { id: 1, name: 'Payroll Set Up', url: '/payroll/settings', icon: '' },
          {
            id: 2,
            name: 'Pay Run',
            url: '/payroll/settings/pay-run',
            icon: '',
          },
          {
            id: 3,
            name: 'Tax Setting',
            url: '/payroll/settings/tax',
            icon: '',
          },
        ],
      },
    ],
  },
  {
    module: [
      'account',
      'budgeting',
      'reports',
      'banking',
      'fixedassets',
      'charts',
      'settings',
    ],
    menus: [
      { id: 1, name: 'Dashboard', url: '/account', icon: 'dashboard' },
      {
        id: 2,
        name: 'Chart of Account',
        url: '/account/charts',
        icon: 'account_tree',
      },
      { id: 3, name: 'Journal', url: '/account/journal', icon: 'menu_book' },
      { id: 4, name: 'Fixed Asset', url: '/account/fixedassets', icon: 'note' },
      {
        id: 5,
        name: 'Banking',
        url: '/account/banking',
        icon: 'account_balance',
      },
      {
        id: 6,
        name: 'Reports',
        url: '/account/reports',
        icon: 'local_library',
      },
      // {
      //   id: 7,
      //   name: 'Budgeting',
      //   url: '/account/budgeting',
      //   icon: 'account_balance_wallet',
      // },
      {
        id: 8,
        name: 'Settings',
        url: '#',
        icon: 'settings',
        submenus: [
          {
            id: 1,
            name: 'Account Settings',
            url: '/account/settings/period',
            icon: '',
          },
          {
            id: 2,
            name: 'Depreciation type',
            url: '/account/settings/depreciation-type',
            icon: '',
          },
          // {
          //   id: 3,
          //   name: 'Depreciation area',
          //   url: '/account/settings/depreciation-area',
          //   icon: '',
          // },
          {
            id: 4,
            name: 'Asset types',
            url: '/account/settings/assettypes',
            icon: '',
          },
          { id: 5, name: 'Taxes', url: '/account/settings/taxes', icon: '' },
          {
            id: 6,
            name: 'Currencies',
            url: '/account/settings/currencies',
            icon: '',
          },
        ],
      },
    ],
  },
  {
    module: ['crm'],
    menus: [
      { id: 1, name: 'Dashboard', url: '/crm/dashboard', icon: 'dashboard' },
      {
        id: 2,
        name: 'Contacts',
        url: '/crm/contacts',
        icon: 'business_center',
      },
      { id: 3, name: 'Companies', url: '/crm/companies', icon: 'find_in_page' },
      { id: 4, name: 'Activities', url: '/crm/activities', icon: 'person' },
      { id: 5, name: 'Schedules', url: '/crm/schedules', icon: 'payment' },
      {
        id: 6,
        name: 'Contact Groups',
        url: '/crm/contact-groups',
        icon: 'announcement',
      },
      { id: 7, name: 'Reports', url: '/crm/reports', icon: 'local_activity' },
      {
        id: 8,
        name: 'Campaigns',
        url: '/crm/campaigns',
        icon: 'local_activity',
      },
      {
        id: 9,
        name: 'Social Media',
        url: '#',
        icon: 'local_activity',
        submenus: [
          { id: 1, name: 'Social Media', url: '/crm/social-media', icon: '' },
          { id: 1, name: 'Set Up', url: '/crm/social-media/setup', icon: '' },
        ],
      },
      {
        id: 10,
        name: 'Leads',
        url: '#',
        icon: 'local_activity',
        submenus: [
          { id: 1, name: 'Leads', url: '/crm/leads', icon: '' },
          { id: 2, name: 'Lead Sources', url: '/crm/leads/sources', icon: '' },
          { id: 3, name: 'Lead Tags', url: '/crm/leads/tags', icon: '' },
          { id: 4, name: 'Lead Stages', url: '/crm/leads/stages', icon: '' },
        ],
      },
    ],
  },
  {
    module: ['lms'],
    menus: [
      { id: 1, name: 'Dashboard', url: '/lms/dashboard', icon: 'dashboard' },
      // { id: 2, name: 'Account & Settings', url: '/lms/account-settings',icon: 'settings'},
      // { id: 3, name: 'Integration', url: '/lms/integration', icon: 'business_center' },
      {
        id: 4,
        name: 'Certificates',
        url: '/lms/certificates',
        icon: 'find_in_page',
      },
      {
        id: 5,
        name: 'Content Management',
        url: '/lms/content-mgt',
        icon: 'library_books',
      },
      { id: 6, name: 'Users', url: '/lms/user', icon: 'person' },
      {
        id: 7,
        name: 'Course Management',
        url: '/lms/courses',
        icon: 'library_books',
      },
      {
        id: 8,
        name: 'Virtual Classrooms',
        url: '/lms/virtual-classrooms',
        icon: 'person',
      },
      { id: 9, name: 'Enrollments', url: '/lms/enrollments', icon: 'person' },
      { id: 10, name: 'Quizzes', url: '/lms/quizzes', icon: 'person' },
      { id: 11, name: 'Category', url: '/lms/category', icon: 'category' },
      // { id: 12, name: 'Attendance', url: '/lms/attendance', icon: 'person' },
    ],
  },
  {
    module: ['inventory', 'sales', 'purchase'],
    menus: [
      {
        id: 2,
        name: 'Inventory',
        url: '#',
        icon: 'label',
        submenus: [
          {
            id: 1,
            name: 'Dashboard',
            url: '/inventory/dashboard',
            icon: 'dashboard',
          },
          {
            id: 2,
            name: 'Warehouses',
            url: '/inventory/warehouses',
            icon: 'storage',
          },
          { id: 3, name: 'Items', url: '/inventory/items', icon: 'label' },
          {
            id: 4,
            name: 'Items Groups',
            url: '/inventory/items/groups',
            icon: 'group_work',
          },
          {
            id: 5,
            name: 'Transfer Orders',
            url: '/inventory/transfers',
            icon: 'transfer_within_a_station',
          },
          {
            id: 6,
            name: 'Adjustments',
            url: '/inventory/adjustments',
            icon: 'equalizer',
          },
          {
            id: 7,
            name: 'Reports',
            url: '/inventory/reports',
            icon: 'assessment',
          },
        ],
      },
      {
        id: 2,
        name: 'Sales',
        url: '#',
        icon: 'label',
        submenus: [
          {
            id: 2,
            name: 'Sales orders',
            url: '/inventory/sales',
            icon: 'storage',
          },
          {
            id: 3,
            name: 'Invoice',
            url: '/inventory/sales/invoice',
            icon: 'label',
          },
          {
            id: 4,
            name: 'Receipts',
            url: '/inventory/sales/receipts',
            icon: 'group_work',
          },
        ],
      },
      {
        id: 2,
        name: 'Purchases',
        url: '#',
        icon: 'label',
        submenus: [
          {
            id: 2,
            name: 'Purchase orders',
            url: '/inventory/purchase',
            icon: 'storage',
          },
          {
            id: 3,
            name: 'Bills',
            url: '/inventory/purchase/bills',
            icon: 'label',
          },
          {
            id: 4,
            name: 'Payments',
            url: '/inventory/purchase/payments',
            icon: 'group_work',
          },
        ],
      },
    ],
  },
  {
    module: ['project-manager'],
    menus: [
      {
        id: 1,
        name: 'Dashboard',
        url: '/project-manager/dashboard',
        icon: 'dashboard',
      },
      // {
      //   id: 2,
      //   name: 'Work order',
      //   url: '#',
      //   icon: 'label',
      //   submenus: [
      //     {
      //       id: 1,
      //       name: 'Dashboard',
      //       url: '/project-manager/dashboard',
      //       icon: '',
      //     },
      //     {
      //       id: 2,
      //       name: 'Work orders',
      //       url: '/project-manager/work-orders',
      //       icon: '',
      //     },
      //     {
      //       id: 3,
      //       name: 'Vendors',
      //       url: '/project-manager/work-orders',
      //       icon: '',
      //     },
      //   ],
      // },
      {
        id: 4,
        name: 'Jobs',
        url: '#',
        icon: 'group_work',
        submenus: [
          { id: 1, name: 'Jobs list', url: '/project-manager/jobs', icon: '' },
          {
            id: 2,
            name: 'Add Job',
            url: '/project-manager/jobs/new',
            icon: '',
          },
        ],
      },
      {
        id: 5,
        name: 'Reports',
        url: '/project-manager/reports',
        icon: 'assessment',
      },
    ],
  },
  {
    module: ['workflow'],
    menus: [
      {
        id: 1,
        name: 'Process Owners',
        url: '/workflow/process-owners',
        icon: 'dashboard',
      },
      {
        id: 2,
        name: 'Workflow Rules',
        url: '/workflow/rules',
        icon: 'assessment',
      },
      {
        id: 3,
        name: 'Severity Models',
        url: '/workflow/severity-models',
        icon: 'assessment',
      },
    ],
  },
];

export default SidebarConfig;
