/*
 *
 * Banking constants
 *
 */

export const DEFAULT_ACTION = 'app/Banking/DEFAULT_ACTION';

export const GET_ACCOUNTING_PERIODS = 'app/Settings/GET_ACCOUNTING_PERIODS';
export const GET_ACCOUNTING_PERIODS_SUCCESS = 'app/Settings/GET_ACCOUNTING_PERIODS_SUCCESS';
export const GET_ACCOUNTING_PERIODS_ERROR = 'app/Settings/GET_ACCOUNTING_PERIODS_ERROR';

export const OPEN_NEW_BANK_ACCOUNT_DIALOG = 'app/Banking/OPEN_NEW_BANK_ACCOUNT_DIALOG';
export const CLOSE_NEW_BANK_ACCOUNT_DIALOG = 'app/Banking/CLOSE_NEW_BANK_ACCOUNT_DIALOG';

export const EDIT_OPEN_ACCOUNT_DIALOG = 'app/Banking/EDIT_OPEN_ACCOUNT_DIALOG';
export const EDIT_CLOSE_ACCOUNT_DIALOG =
    'app/Banking/EDIT_CLOSE_ACCOUNT_DIALOG';

export const OPEN_DELETE_BANK_ACCOUNT_DIALOG =
    'app/Banking/OPEN_DELETE_BANK_ACCOUNT_DIALOG';
export const CLOSE_DELETE_BANK_ACCOUNT_DIALOG =
    'app/Banking/CLOSE_DELETE_BANK_ACCOUNT_DIALOG';

export const OPEN_ACTIVATE_BANK_ACCOUNT_DIALOG =
    'app/Banking/OPEN_ACTIVATE_BANK_ACCOUNT_DIALOG';
export const CLOSE_ACTIVATE_BANK_ACCOUNT_DIALOG =
    'app/Banking/CLOSE_ACTIVATE_BANK_ACCOUNT_DIALOG';

export const OPEN_DEACTIVATE_BANK_ACCOUNT_DIALOG =
    'app/Banking/OPEN_DEACTIVATE_BANK_ACCOUNT_DIALOG';
export const CLOSE_DEACTIVATE_BANK_ACCOUNT_DIALOG =
    'app/Banking/CLOSE_DEACTIVATE_BANK_ACCOUNT_DIALOG';

export const GET_CURRENCIES = 'app/Settings/GET_CURRENCIES';
export const GET_CURRENCIES_SUCCESS = 'app/Settings/GET_CURRENCIES_SUCCESS';
export const GET_CURRENCIES_ERROR = 'app/Settings/GET_CURRENCIES_ERROR';

export const GET_ALL_ACCOUNT_TYPES = 'app/Banking/GET_ALL_ACCOUNT_TYPES';
export const GET_ALL_ACCOUNT_TYPES_SUCCESS =
    'app/Banking/GET_ALL_ACCOUNT_TYPES_SUCCESS';
export const GET_ALL_ACCOUNT_TYPES_ERR =
    'app/Banking/GET_ALL_ACCOUNT_TYPES_ERR';

export const CREATE_NEW_BANK = 'app/Banking/CREATE_NEW_BANK';
export const CREATE_NEW_BANK_SUCCESS = 'app/Banking/CREATE_NEW_BANK_SUCCESS';
export const CREATE_NEW_BANK_ERR = 'app/Banking/CREATE_NEW_BANK_ERR';

export const GET_ALL_BANK_ACCOUNT = 'app/Banking/GET_ALL_BANK_ACCOUNT';
export const GET_ALL_BANK_ACCOUNT_SUCCESS =
    'app/Banking/GET_ALL_BANK_ACCOUNT_SUCCESS';
export const GET_ALL_BANK_ACCOUNT_ERR = 'app/Banking/GET_ALL_BANK_ACCOUNT_ERR';

export const GET_BANK_ACCOUNT_BY_ID = 'app/Banking/GET_BANK_ACCOUNT_BY_ID';
export const GET_BANK_ACCOUNT_BY_ID_SUCCESS =
    'app/Banking/GET_BANK_ACCOUNT_BY_ID_SUCCESS';
export const GET_BANK_ACCOUNT_BY_ID_ERROR =
    'app/Banking/GET_BANK_ACCOUNT_BY_ID_ERROR';

export const UPDATE_BANK_ACCOUNT = 'app/Banking/UPDATE_BANK_ACCOUNT';
export const UPDATE_BANK_ACCOUNT_SUCCESS =
    'app/Banking/UPDATE_BANK_ACCOUNT_SUCCESS';
export const UPDATE_BANK_ACCOUNT_ERR = 'app/Banking/UPDATE_BANK_ACCOUNT_ERR';

export const GET_ALL_TRANSFER_BY_ORGID =
    'app/Banking/GET_ALL_TRANSFER_BY_ORGID';
export const GET_ALL_TRANSFER_BY_ORGID_SUCCESS =
    'app/Banking/GET_ALL_TRANSFER_BY_ORGID_SUCCESS';
export const GET_ALL_TRANSFER_BY_ORGID_ERR =
    'app/Banking/GET_ALL_TRANSFER_BY_ORGID_ERR';

export const OPEN_ACCOUNT_TRANSFER_DIALOG =
    'app/Banking/OPEN_ACCOUNT_TRANSFER_DIALOG';
export const CLOSE_ACCOUNT_TRANSFER_DIALOG =
    'app/Banking/CLOSE_ACCOUNT_TRANSFER_DIALOG';

export const CREATE_BANK_TRANSFER = 'app/Banking/CREATE_BANK_TRANSFER';
export const CREATE_BANK_TRANSFER_SUCCESS =
    'app/Banking/CREATE_BANK_TRANSFER_SUCCESS';
export const CREATE_BANK_TRANSFER_ERR = 'app/Banking/CREATE_BANK_TRANSFER_ERR';

export const GET_TRANSFERS_BY_ACCOUNT_ID =
    'app/Banking/GET_TRANSFERS_BY_ACCOUNT_ID';
export const GET_TRANSFERS_BY_ACCOUNT_ID_SUCCESS =
    'app/Banking/GET_TRANSFERS_BY_ACCOUNT_ID_SUCCESS';
export const GET_TRANSFERS_BY_ACCOUNT_ID_ERR =
    'app/Banking/GET_TRANSFERS_BY_ACCOUNT_ID_ERR';

export const ACTIVATE_DEACTIVATE_BANK_ACCOUNT =
    'app/Banking/ACTIVATE_DEACTIVATE_BANK_ACCOUNT';
export const ACTIVATE_DEACTIVATE_BANK_ACCOUNT_SUCCESS =
    'app/Banking/ACTIVATE_DEACTIVATE_BANK_ACCOUNT_SUCCESS';
export const ACTIVATE_DEACTIVATE_BANK_ACCOUNT_ERR =
    'app/Banking/ACTIVATE_DEACTIVATE_BANK_ACCOUNT_ERR';

export const DELETE_BANK_ACCOUNT = 'app/Banking/DELETE_BANK_ACCOUNT';
export const DELETE_BANK_ACCOUNT_SUCCESS =
    'app/Banking/DELETE_BANK_ACCOUNT_SUCCESS';
export const DELETE_BANK_ACCOUNT_ERR = 'app/Banking/DELETE_BANK_ACCOUNT_ERR';
