/*
 *
 * Banking constants
 *
 */

export const DEFAULT_ACTION = 'app/Banking/DEFAULT_ACTION';


export const OPEN_NEW_BANK_ACCOUNT_DIALOG = 'app/Banking/OPEN_NEW_BANK_ACCOUNT_DIALOG';
export const CLOSE_NEW_BANK_ACCOUNT_DIALOG = 'app/Banking/CLOSE_NEW_BANK_ACCOUNT_DIALOG';

export const EDIT_OPEN_ACCOUNT_DIALOG = 'app/Banking/EDIT_OPEN_ACCOUNT_DIALOG';
export const EDIT_CLOSE_ACCOUNT_DIALOG = 'app/Banking/EDIT_CLOSE_ACCOUNT_DIALOG';

export const GET_ALL_ACCOUNT_TYPES = 'app/Banking/GET_ALL_ACCOUNT_TYPES';
export const GET_ALL_ACCOUNT_TYPES_SUCCESS = 'app/Banking/GET_ALL_ACCOUNT_TYPES_SUCCESS';
export const GET_ALL_ACCOUNT_TYPES_ERR = 'app/Banking/GET_ALL_ACCOUNT_TYPES_ERR';

export const CREATE_NEW_BANK = 'app/Banking/CREATE_NEW_BANK';
export const CREATE_NEW_BANK_SUCCESS = 'app/Banking/CREATE_NEW_BANK_SUCCESS';
export const CREATE_NEW_BANK_ERR = 'app/Banking/CREATE_NEW_BANK_ERR';

export const GET_ALL_BANK_ACCOUNT = 'app/Banking/GET_ALL_BANK_ACCOUNT';
export const GET_ALL_BANK_ACCOUNT_SUCCESS = 'app/Banking/GET_ALL_BANK_ACCOUNT_SUCCESS';
export const GET_ALL_BANK_ACCOUNT_ERR = 'app/Banking/GET_ALL_BANK_ACCOUNT_ERR';

export const UPDATE_BANK_ACCOUNT = 'app/Banking/UPDATE_BANK_ACCOUNT';
export const UPDATE_BANK_ACCOUNT_SUCCESS = 'app/Banking/UPDATE_BANK_ACCOUNT_SUCCESS';
export const UPDATE_BANK_ACCOUNT_ERR = 'app/Banking/UPDATE_BANK_ACCOUNT_ERR';