/*
 *
 * LMS Students constants
 *
 */

export const OPEN_NEW_STUDENT_DIALOG = 'app/LMS/OPEN_NEW_STUDENT_DIALOG';
export const CLOSE_NEW_STUDENT_DIALOG = 'app/LMS/CLOSE_NEW_STUDENT_DIALOG';

export const OPEN_EDIT_STUDENT_DIALOG = 'app/LMS/OPEN_EDIT_STUDENT_DIALOG';
export const CLOSE_EDIT_STUDENT_DIALOG = 'app/LMS/CLOSE_EDIT_STUDENT_DIALOG';

export const CREATE_STUDENT = 'app/LMS/CREATE_STUDENT';
export const CREATE_STUDENT_SUCCESS = 'app/LMS/CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_ERROR = 'app/LMS/CREATE_STUDENT_ERROR';

export const UPDATE_STUDENT = 'app/LMS/UPDATE_STUDENT';
export const UPDATE_STUDENT_SUCCESS = 'app/LMS/UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_ERROR = 'app/LMS/UPDATE_STUDENT_ERROR';

export const GET_STUDENTS = 'app/LMS/GET_STUDENTS';
export const GET_STUDENTS_SUCCESS = 'app/LMS/GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_ERROR = 'app/LMS/GET_STUDENTS_ERROR';
