/*
 *
 * UtilityPage constants
 *
 */

export const OPEN_FILE_UPLOAD_DIALOG =
  'app/UtilityPage/OPEN_FILE_UPLOAD_DIALOG';
export const CLOSE_FILE_UPLOAD_DIALOG =
  'app/UtilityPage/CLOSE_FILE_UPLOAD_DIALOG';

export const OPEN_SHARE_FILE_DIALOG = 'app/UtilityPage/OPEN_SHARE_FILE_DIALOG';
export const CLOSE_SHARE_FILE_DIALOG =
  'app/UtilityPage/CLOSE_SHARE_FILE_DIALOG';

export const OPEN_PREVIEW_FILE_DIALOG =
  'app/UtilityPage/OPEN_PREVIEW_FILE_DIALOG';
export const CLOSE_PREVIEW_FILE_DIALOG =
  'app/UtilityPage/CLOSE_PREVIEW_FILE_DIALOG';

export const OPEN_NEW_TASK_DIALOG = 'app/UtilityPage/OPEN NEW TASK DIALOG';
export const CLOSE_NEW_TASK_DIALOG = 'app/UtilityPage/CLOSE NEW TASK DIALOG';
export const OPEN_EDIT_TASK_DIALOG = 'app/UtilityPage/OPEN EDIT TASK DIALOG';
export const CLOSE_EDIT_TASK_DIALOG = 'app/UtilityPage/CLOSE EDIT TASK DIALOG';
export const OPEN_ASSIGN_TO_DIALOG = 'app/UtilityPage/OPEN ASSIGN TO DIALOG';
export const CLOSE_ASSIGN_TO_DIALOG = 'app/UtilityPage/CLOSE EDIT TASK DIALOG';

export const OPEN_NEW_FILE_DIALOG = 'app/UtilityPage/OPEN NEW FILE DIALOG';
export const CLOSE_NEW_FILE_DIALOG = 'app/UtilityPage/CLOSE NEW FILE DIALOG';
export const OPEN_NEW_FOLDER_DIALOG = 'app/UtilityPage/OPEN NEW FOLDER DIALOG';
export const CLOSE_NEW_FOLDER_DIALOG = 'app/UtilityPage/CLOSE NEW FOLDER DIALOG';

export const OPEN_TASK_PREVIEW_DIALOG =
  'app/UtilityPage/OPEN_TASK_PREVIEW_DIALOG';
export const CLOSE_TASK_PREVIEW_DIALOG =
  'app/UtilityPage/CLOSE_TASK_PREVIEW_DIALOG';

export const OPEN_NEW_BRANCH_DIALOG = 'app/UtilityPage/OPEN_NEW_BRANCH_DIALOG';
export const CLOSE_NEW_BRANCH_DIALOG =
  'app/UtilityPage/CLOSE_NEW_BRANCH_DIALOG';
export const OPEN_EDIT_BRANCH_DIALOG =
  'app/UtilityPage/OPEN_EDIT_BRANCH_DIALOG';
export const CLOSE_EDIT_BRANCH_DIALOG =
  'app/UtilityPage/CLOSE_EDIT_BRANCH_DIALOG';

export const OPEN_NEW_DEPARTMENT_DIALOG =
  'app/OrgPage/OPEN_NEW_DEPARTMENT_DIALOG';
export const CLOSE_NEW_DEPARTMENT_DIALOG =
  'app/OrgPage/CLOSE_NEW_DEPARTMENT_DIALOG';
export const OPEN_EDIT_DEPARTMENT_DIALOG =
  'app/OrgPage/OPEN_EDIT_DEPARTMENT_DIALOG';
export const CLOSE_EDIT_DEPARTMENT_DIALOG =
  'app/OrgPage/CLOSE_EDIT_DEPARTMENT_DIALOG';

// UTILITY CONSTANTS
export const GET_UTILITY_APPS = 'app/UtilityPage/GET UTILITY APPS';
export const GET_UTILITY_APPS_SUCCESS =
  'app/UtilityPage/GET UTILITY APPS SUCCESS';
export const GET_UTILITY_APPS_ERROR = 'app/UtilityPage/GET UTILITY APPS ERROR';

export const ADD_TASK_COMMENT = 'app/UtilityPage/ADD TASK COMMENT';
export const ADD_TASK_COMMENT_SUCCESS = 'app/UtilityPage/ADD TASK COMMENT SUCCESS';
export const ADD_TASK_COMMENT_ERROR = 'app/UtilityPage/ADD TASK COMMENT ERROR';
export const GET_TASK_COMMENTS = 'app/UtilityPage/GET TASK COMMENTS';
export const GET_TASK_COMMENTS_SUCCESS = 'app/UtilityPage/GET TASK COMMENTS SUCCESS';
export const ADD_TASK_ATTACHMENT = 'app/UtilityPage/ADD TASK ATTACHMENT';
export const ADD_TASK_ATTACHMENT_SUCCESS = 'app/UtilityPage/ADD TASK ATTACHMENT SUCCESS';
export const DELETE_TASK = 'app/UtilityPage/DELETE TASK';
export const DELETE_TASK_SUCCESS = 'app/UtilityPage/DELETE TASK SUCCESS';
export const REMOVE_TASK_ATTACHMENT = 'app/UtilityPage/REMOVE TASK ATTACHMENT';
export const REMOVE_TASK_ATTACHMENT_SUCCESS = 'app/UtilityPage/REMOVE TASK ATTACHMENT SUCCESS';
export const GET_UTILITY_TASK = 'app/UtilityPage/GET UTILITY TASK';
export const GET_UTILITY_TASK_SUCCESS = 'app/UtilityPage/GET UTILITY TASK SUCCESS';
export const GET_UTILITY_TASKS = 'app/UtilityPage/GET UTILITY TASKS';
export const GET_UTILITY_TASKS_SUCCESS = 'app/UtilityPage/GET ALL UTILITY TASKS SUCCESS';
export const UPDATE_UTILITY_TASK = 'app/UtilityPage/UPDATE UTILITY TASK';
export const UPDATE_UTILITY_TASK_SUCCESS = 'app/UtilityPage/UPDATE UTILITY TASK SUCCESS';
export const GET_UTILITY_TASKS_BY_STATUS = 'app/UtilityPage/GET UTILITY TASKS BY STATUS';
export const GET_UTILITY_TASKS_BY_STATUS_SUCCESS = 'app/UtilityPage/GET ALL UTILITY TASKS BY STATUS SUCCESS';
export const CREATE_UTILITY_TASKS = 'app/UtilityPage/CREATE UTILITY TASKS';
export const CREATE_UTILITY_TASKS_SUCCESS = 'app/UtilityPage/CREATE UTILITY TASKS SUCCESS';
export const CREATE_UTILITY_TASKS_ERROR = 'app/UtilityPage/CREATE UTILITY TASKS ERROR';
export const GET_UTILITY_TASKS_ERROR = 'app/UtilityPage/GET UTILITY TASKS ERROR';
export const GET_ASSIGNEDTO_BY_UUID = 'app/UtilityPage/GET ASSIGNEDTO BY UUID';
export const GET_ASSIGNEDTO_BY_UUID_SUCCESS = 'app/UtilityPage/GET ASSIGNEDTO BY UUID SUCCESS';

export const ADD_DOC_TO_FOLDER = 'app/UtilityPage/ADD DOC TO FOLDER';
export const ADD_DOC_TO_FOLDER_SUCCESS = 'app/UtilityPage/ADD DOC TO FOLDER SUCCESS';
export const ADD_FOLDER_TO_FOLDER = 'app/UtilityPage/ADD FOLDER TO FOLDER';
export const ADD_FOLDER_TO_FOLDER_SUCCESS = 'app/UtilityPage/ADD FOLDER TO FOLDER SUCCESS';
export const GET_FOLDER_BY_ID = 'app/UtilityPage/GET FOLDER BY ID';
export const GET_FOLDER_BY_ID_SUCCESS = 'app/UtilityPage/GET FOLDER BY ID SUCCESS';
export const GET_UTILITY_FILE = 'app/UtilityPage/GET UTILITY FILE';
export const GET_UTILITY_FILE_SUCCESS = 'app/UtilityPage/GET UTILITY FILE SUCCESS';
export const GET_UTILITY_FILES = 'app/UtilityPage/GET UTILITY FILES';
export const GET_UTILITY_FILES_SUCCESS = 'app/UtilityPage/GET UTILITY FILES SUCCESS';
export const GET_FOLDERS_AND_DOC = 'app/UtilityPage/GET UTILITY FOLDERS AND DOC';
export const GET_FOLDERS_AND_DOC_SUCCESS = 'app/UtilityPage/GET UTILITY FOLDERS AND DOC SUCCESS';
export const GET_NESTED_FOLDERS_AND_DOC = 'app/UtilityPage/GET UTILITY NESTED FOLDERS AND DOC';
export const GET_NESTED_FOLDERS_AND_DOC_SUCCESS = 'app/UtilityPage/GET UTILITY NESTED FOLDERS AND DOC SUCCESS';

export const DELETE_DOCUMENT = 'app/UtilityPage/DELETE DOCUMENT SUCCESS';
export const DELETE_DOCUMENT_SUCCESS = 'app/UtilityPage/DELETE DOCUMENT SUCCESS';
export const SHARE_DOCUMENT = 'app/UtilityPage/SHARE DOCUMENT';
export const SHARE_DOCUMENT_SUCCESS = 'app/UtilityPage/SHARE DOCUMENT SUCCESS';
export const GET_SHARED_DOCS_BY_UUID = 'app/UtilityPage/GET SHARED DOCS BY UUID';
export const GET_SHARED_DOCS_BY_UUID_SUCCESS = 'app/UtilityPage/GET SHARED DOCS BY UUID SUCCESS';
export const GET_FAVORITE_DOCS_BY_UUID = 'app/UtilityPage/GET FAVORITE DOCS BY UUID';
export const GET_FAVORITE_DOCS_BY_UUID_SUCCESS = 'app/UtilityPage/GET FAVORITE DOCS BY UUID SUCCESS';
export const FAVORITE_FILE_BY_DOC_ID = 'app/UtilityPage/FAVORITE FILE BY DOC ID';
export const FAVORITE_FILE_BY_DOC_ID_SUCCESS = 'app/UtilityPage/FAVORITE FILE BY DOC ID SUCCESS';
export const UNFAVORITE_FILE_BY_DOC_ID = 'app/UtilityPage/UNFAVORITE FILE BY DOC ID';
export const UNFAVORITE_FILE_BY_DOC_ID_SUCCESS = 'app/UtilityPage/UNFAVORITE FILE BY DOC ID SUCCESS';
export const CREATE_UTILITY_FILES = 'app/UtilityPage/CREATE UTILITY FILES';
export const CREATE_UTILITY_FILES_SUCCESS = 'app/UtilityPage/CREATE UTILITY FILES SUCCESS';
export const GET_UTILITY_FILES_ERROR = 'app/UtilityPage/GET UTILITY FILES ERROR';

export const GET_EMPLOYEES = 'app/UtilityPage/GET EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'app/UtilityPage/GET EMPLOYEES SUCCESS';

export const GET_UTILITY_CHATS = 'app/UtilityPage/GET UTILITY CHATS ';
export const CREATE_UTILITY_CHATS_SUCCESS =
  'app/UtilityPage/CREATE UTILITY CHATS SUCCESS';
export const GET_UTILITY_CHATS_ERROR =
  'app/UtilityPage/GET UTILITY CHATS ERROR';

// get all employee
export const GET_ALL_USERS = 'app/UtilityPage/GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'app/UtilityPage/GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_ERROR = 'app/UtilityPage/GET_ALL_USERS_ERROR';

export const GET_USER_BY_UUID = 'app/UtilityPage/GET USER BY UUID';
export const GET_USER_BY_UUID_SUCCESS =
  'app/UtilityPage/GET USER BY UUID SUCCESS';

export const GET_ALL_USERS_CHAT = 'app/UtilityPage/GET_ALL_USERS_CHAT';
export const GET_ALL_USERS_CHAT_SUCCESS =
  'app/UtilityPage/GET_ALL_USERS_CHAT_SUCCESS';
export const GET_ALL_USERS_CHAT_ERROR =
  'app/UtilityPage/GET_ALL_USERS_CHAT_ERROR';

export const GET_USER_CHAT_DATA = 'app/UtilityPage/GET_USER_CHAT_DATA';
export const GET_USER_CHAT_DATA_SUCCESS =
  'app/UtilityPage/GET_USER_CHAT_DATA_SUCCESS';
export const GET_USER_CHAT_DATA_ERROR =
  'app/UtilityPage/GET_USER_CHAT_DATA_ERROR';

export const POST_MSG = 'app/UtilityPage/POST_MSG';
export const POST_MSG_SUCCESS = 'app/UtilityPage/POST_MSG_SUCCESS';
export const POST_MSG_ERROR = 'app/UtilityPage/POST_MSG_ERROR';
