/*
 *
 * Companies constants
 *
 */

export const OPEN_NEW_ENROLLMENT_DIALOG = 'app/LMS/OPEN NEW ENROLLMENT DIALOG';
export const CLOSE_NEW_ENROLLMENT_DIALOG = 'app/LMS/CLOSE NEW ENROLLMENT DIALOG';

export const OPEN_EDIT_ENROLLMENT_DIALOG = 'app/LMS/OPEN EDIT ENROLLMENT DIALOG';
export const CLOSE_EDIT_ENROLLMENT_DIALOG = 'app/LMS/CLOSE EDIT ENROLLMENT DIALOG';

export const GET_ENROLLMENTS = 'app/LMS/GET ENROLLMENTS';
export const GET_ENROLLMENTS_SUCCESS = 'app/LMS/GET ENROLLMENTS SUCCESS';
export const GET_ENROLLMENTS_ERROR = 'app/LMS/GET ENROLLMENTS ERROR';

export const CREATE_ENROLLMENT = 'app/LMS/CREATE ENROLLMENT';
export const CREATE_ENROLLMENT_SUCCESS = 'app/LMS/CREATE ENROLLMENT SUCCESS';
export const CREATE_ENROLLMENT_ERROR = 'app/LMS/CREATE ENROLLMENT ERROR';

export const UPDATE_ENROLLMENT = 'app/LMS/UPDATE ENROLLMENT';
export const UPDATE_ENROLLMENT_SUCCESS = 'app/LMS/UPDATE ENROLLMENT SUCCESS';
export const UPDATE_ENROLLMENT_ERROR = 'app/LMS/UPDATE ENROLLMENT ERROR';
