/*
 *
 * Salary Advance constants
 *
 */

export const GET_PAYROLL_SETUP = 'app/Settings/GET_PAYROLL_SETUP';
export const GET_PAYROLL_SETUP_SUCCESS = 'app/Settings/GET_PAYROLL_SETUP_SUCCESS';
export const GET_PAYROLL_SETUP_ERROR = 'app/Settings/GET_PAYROLL_SETUP_ERROR';

export const OPEN_NEW_SALARY_ADVANCE_DIALOG = 'app/SalaryAdvance/OPEN_NEW_SALARY_ADVANCE_DIALOG';
export const CLOSE_NEW_SALARY_ADVANCE_DIALOG = 'app/SalaryAdvance/CLOSE_NEW_SALARY_ADVANCE_DIALOG';

export const OPEN_EDIT_SALARY_ADVANCE_DIALOG = 'app/SalaryAdvance/OPEN_NEW_SALARY_ADVANCE_DIALOG';
export const CLOSE_EDIT_SALARY_ADVANCE_DIALOG = 'app/SalaryAdvance/CLOSE_NEW_SALARY_ADVANCE_DIALOG';

export const OPEN_DELETE_SALARY_ADVANCE_DIALOG = 'app/SalaryAdvance/OPEN_DELETE_SALARY_ADVANCE_DIALOG';
export const CLOSE_DELETE_SALARY_ADVANCE_DIALOG = 'app/SalaryAdvance/CLOSE_DELETE_SALARY_ADVANCE_DIALOG';

export const CREATE_SALARY_ADVANCE = 'app/SalaryAdvance/CREATE_SALARY_ADVANCE';
export const CREATE_SALARY_ADVANCE_SUCCESS = 'app/SalaryAdvance/CREATE_SALARY_ADVANCE_SUCCESS';
export const CREATE_SALARY_ADVANCE_ERROR = 'app/SalaryAdvance/CREATE_SALARY_ADVANCE_ERROR';

export const GET_SALARY_ADVANCES = 'app/SalaryAdvance/GET_SALARY_ADVANCES';
export const GET_SALARY_ADVANCES_SUCCESS = 'app/SalaryAdvance/GET_SALARY_ADVANCES_SUCCESS';
export const GET_SALARY_ADVANCES_ERROR = 'app/SalaryAdvance/GET_SALARY_ADVANCES_ERROR';

export const GET_SALARY_ADVANCE_BY_ID = 'app/SalaryAdvance/GET_SALARY_ADVANCE_BY_ID';
export const GET_SALARY_ADVANCE_BY_ID_SUCCESS = 'app/SalaryAdvance/GET_SALARY_ADVANCE_BY_ID_SUCCESS';
export const GET_SALARY_ADVANCE_BY_ID_ERROR = 'app/SalaryAdvance/GET_SALARY_ADVANCE_BY_ID_ERROR';

export const UPDATE_SALARY_ADVANCE = 'app/SalaryAdvance/UPDATE_SALARY_ADVANCE';
export const UPDATE_SALARY_ADVANCE_SUCCESS = 'app/SalaryAdvance/UPDATE_SALARY_ADVANCE_SUCCESS';
export const UPDATE_SALARY_ADVANCE_ERROR = 'app/SalaryAdvance/UPDATE_SALARY_ADVANCE_ERR';

export const DELETE_SALARY_ADVANCE = 'app/SalaryAdvance/DELETE_SALARY_ADVANCE';
export const DELETE_SALARY_ADVANCE_SUCCESS = 'app/SalaryAdvance/DELETE_SALARY_ADVANCE_SUCCESS';
export const DELETE_SALARY_ADVANCE_ERROR = 'app/SalaryAdvance/DELETE_SALARY_ADVANCE_ERR';
