/*
 *
 * Crm Contact Groups constants
 *
 */

export const OPEN_NEW_CONTACT_GROUPS_DIALOG =
  'app/Crm/OPEN_NEW_CONTACT_GROUPS_DIALOG';
export const CLOSE_NEW_CONTACT_GROUPS_DIALOG =
  'app/Crm/CLOSE_NEW_CONTACT_GROUPS_DIALOG';

export const OPEN_EDIT_CONTACT_GROUPS_DIALOG =
  'app/Crm/OPEN_EDIT_CONTACT_GROUPS_DIALOG';
export const CLOSE_EDIT_CONTACT_GROUPS_DIALOG =
  'app/Crm/CLOSE_EDIT_CONTACT_GROUPS_DIALOG';

export const OPEN_ASSIGN_CONTACT_DIALOG = 'app/Crm/OPEN_ASSIGN_CONTACT_DIALOG';
export const CLOSE_ASSIGN_CONTACT_DIALOG =
  'app/Crm/CLOSE_ASSIGN_CONTACT_DIALOG';

export const CREATE_NEW_CONTACT_GROUP = 'app/Crm/CREATE_NEW_CONTACT_GROUP';
export const CREATE_NEW_CONTACT_GROUP_SUCCESS =
  'app/Crm/CREATE_NEW_CONTACT_GROUP_SUCCESS';
export const CREATE_NEW_CONTACT_GROUP_ERROR =
  'app/Crm/CREATE_NEW_CONTACT_GROUP_ERROR';

export const UPDATE_CONTACT_GROUP = 'app/Crm/UPDATE_CONTACT_GROUP';
export const UPDATE_CONTACT_GROUP_SUCCESS =
  'app/Crm/UPDATE_CONTACT_GROUP_SUCCESS';
export const UPDATE_CONTACT_GROUP_ERROR = 'app/Crm/UPDATE_CONTACT_GROUP_ERROR';

export const GET_ALL_CONTACTS_GROUP = 'app/Crm/GET_ALL_CONTACTS_GROUP';
export const GET_ALL_CONTACTS_GROUP_SUCCESS =
  'app/Crm/GET_ALL_CONTACTS_GROUP_SUCCESS';
export const GET_ALL_CONTACTS_GROUP_ERROR =
  'app/Crm/GET_ALL_CONTACTS_GROUP_ERROR';

export const GET_CONTACT_GROUP_BY_ID = 'app/Crm/GET_CONTACT_GROUP_BY_ID';
export const GET_CONTACT_GROUP_BY_ID_SUCCESS =
  'app/Crm/GET_CONTACT_GROUP_BY_ID_SUCCESS';
export const GET_CONTACT_GROUP_BY_ID_ERROR =
  'app/Crm/GET_CONTACT_GROUP_BY_ID_ERROR';

export const ASSIGN_CONTACT_TO_GROUP = 'app/Crm/ASSIGN_CONTACT_TO_GROUP';
export const ASSIGN_CONTACT_TO_GROUP_SUCCESS =
  'app/Crm/ASSIGN_CONTACT_TO_GROUP_SUCCESS';
export const ASSIGN_CONTACT_TO_GROUP_ERROR =
  'app/Crm/ASSIGN_CONTACT_TO_GROUP_ERROR';

export const GET_ALL_CONTACTS = 'app/Crm/GET_ALL_CONTACTS';
export const GET_ALL_CONTACTS_SUCCESS = 'app/Crm/GET_ALL_CONTACTS_SUCCESS';
export const GET_ALL_CONTACTS_ERROR = 'app/Crm/GET_ALL_CONTACTS_ERROR';
