export const GET_ALL_EMPLOYEES = 'app/UsersPage/GET_ALL_EMPLOYEES';
export const GET_ALL_EMPLOYEES_SUCCESS =
  'app/UsersPage/GET_ALL_EMPLOYEES_SUCCESS';
export const GET_ALL_EMPLOYEES_ERROR = 'app/UsersPage/GET_ALL_EMPLOYEES_ERROR';

export const GET_PAGED_EMPLOYEES = 'app/UsersPage/GET PAGED EMPLOYEES';
export const GET_PAGED_EMPLOYEES_SUCCESS =
  'app/UsersPage/GET PAGED EMPLOYEES SUCCESS';
export const GET_PAGED_EMPLOYEES_ERROR =
  'app/UsersPage/GET PAGED EMPLOYEES ERROR';

export const OPEN_NEW_EMPLOYEE_DIALOG =
  'app/UsersPage/OPEN_NEW_EMPLOYEE_DIALOG';
export const CLOSE_NEW_EMPLOYEE_DIALOG =
  'app/UsersPage/CLOSE_NEW_EMPLOYEE_DIALOG';

export const OPEN_EDIT_EMPLOYEE_DIALOG =
  'app/UsersPage/OPEN_EDIT_EMPLOYEE_DIALOG';
export const CLOSE_EDIT_EMPLOYEE_DIALOG =
  'app/UsersPage/CLOSE_EDIT_EMPLOYEE_DIALOG';

export const OPEN_VIEW_EMPLOYEE_DIALOG =
  'app/UsersPage/OPEN_VIEW_EMPLOYEE_DIALOG';
export const CLOSE_VIEW_EMPLOYEE_DIALOG =
  'app/UsersPage/CLOSE_VIEW_EMPLOYEE_DIALOG';

export const CREATE_NEW_EMPLOYEE = 'app/UsersPage/CREATE_NEW_EMPLOYEE';
export const CREATE_NEW_EMPLOYEE_SUCCESS =
  'app/UsersPage/CREATE_NEW_EMPLOYEE_SUCCESS';
export const CREATE_NEW_EMPLOYEE_ERROR =
  'app/UsersPage/CREATE_NEW_EMPLOYEE_ERROR';

export const UPDATE_EMPLOYEE = 'app/UsersPage/UPDATE EMPLOYEE';
export const UPDATE_EMPLOYEE_SUCCESS = 'app/UsersPage/UPDATE EMPLOYEE SUCCESS';
export const UPDATE_EMPLOYEE_ERROR = 'app/UsersPage/UPDATE EMPLOYEE ERROR';

export const DELETE_EMPLOYEE = 'app/UsersPage//DELETE EMPLOYEE';
export const DELETE_EMPLOYEE_SUCCESS = 'app/UsersPage/DELETE EMPLOYEE SUCCESS';
export const DELETE_EMPLOYEE_ERROR = 'app/UsersPage/DELETE EMPLOYEE ERROR';

export const OPEN_CONFIRM_DELETE_EMPLOYEE_DIALOG =
  'boilerplate/HRPage/OPEN CONFIRM DELETE EMPLOYEE DIALOG';
export const CLOSE_CONFIRM_DELETE_EMPLOYEE_DIALOG =
  'boilerplate/HRPage/CLOSE CONFIRM DELETE EMPLOYEE DIALOG';

export const GET_BRANCHES = 'app/UsersPage/GET_BRANCHES';
export const GET_BRANCHES_SUCCESS = 'app/UsersPage/GET_BRANCHES_SUCCESS';
export const GET_BRANCHES_ERROR = 'app/UsersPage/GET_BRANCHES_ERROR';

export const GET_POSITIONS = 'boilerplate/HRPage/GET_POSITIONS';
export const GET_POSITIONS_SUCCESS = 'boilerplate/HRPage/GET_POSITIONS_SUCCESS';
export const GET_POSITIONS_ERROR = 'boilerplate/HRPage/GET_POSITIONS_ERROR';

export const GET_DEPARTMENTS = 'boilerplate/HRPage/GET_DEPARTMENTS';
export const GET_DEPARTMENTS_SUCCESS =
  'boilerplate/HRPage/GET_DEPARTMENTS_SUCCESS';
export const GET_DEPARTMENTS_ERROR = 'boilerplate/HRPage/GET_DEPARTMENTS_ERROR';

export const GET_EMPLOYEETYPES = 'boilerplate/HRPage/GET EMPLOYEETYPES';
export const GET_EMPLOYEETYPES_SUCCESS =
  'boilerplate/HRPage/GET EMPLOYEETYPES SUCCESS';
export const GET_EMPLOYEETYPES_ERROR =
  'boilerplate/HRPage/GET EMPLOYEETYPES ERROR';

export const GET_SOURCE_OF_HIRE = 'boilerplate/HRPage/GET SOURCE OF HIRE';
export const GET_SOURCE_OF_HIRE_SUCCESS =
  'boilerplate/HRPage/GET GET SOURCE OF HIRE SUCCESS';
export const GET_SOURCE_OF_HIRE_ERROR =
  'boilerplate/HRPage/GET GET SOURCE OF HIRE ERROR';

export const GET_PAY_RATES = 'boilerplate/HRPage/GET PAY RATES';
export const GET_PAY_RATES_SUCCESS = 'boilerplate/HRPage/GET PAY RATES SUCCESS';
export const GET_PAY_RATES_ERROR = 'boilerplate/HRPage/GET PAY RATES ERROR';

export const GET_PAY_TYPES = 'boilerplate/HRPage/GET PAY TYPES';
export const GET_PAY_TYPES_SUCCESS = 'boilerplate/HRPage/GET PAY TYPES SUCCESS';
export const GET_PAY_TYPES_ERROR = 'boilerplate/HRPage/GET PAY TYPES ERROR';

export const OPEN_SIGNATURE_DIALOG = 'app/UsersPage/OPEN_SIGNATURE_DIALOG';
export const CLOSE_SIGNATURE_DIALOG = 'app/UsersPage/CLOSE_SIGNATURE_DIALOG';

export const OPEN_EDIT_USER_PROFILE_DIALOG =
  'app/UsersPage/OPEN_EDIT_USER_PROFILE_DIALOG';
export const CLOSE_EDIT_USER_PROFILE_DIALOG =
  'app/UsersPage/CLOSE_EDIT_USER_PROFILE_DIALOG';

export const UPDATE_USER_PROFILE = 'app/UsersPage/UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_SUCCESS =
  'app/UsersPage/UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_ERROR =
  'app/UsersPage/UPDATE_USER_PROFILE_ERROR';
