/*
 *
 * Course Management constants
 *
 */

export const OPEN_NEW_ASSIGNMENT_DIALOG = 'app/LMS/OPEN_NEW_ASSIGNMENT_DIALOG';
export const CLOSE_NEW_ASSIGNMENT_DIALOG = 'app/LMS/CLOSE_NEW_ASSIGNMENT_DIALOG';

export const OPEN_EDIT_ASSIGNMENT_DIALOG = 'app/LMS/OPEN_EDIT_ASSIGNMENT_DIALOG';
export const CLOSE_EDIT_ASSIGNMENT_DIALOG = 'app/LMS/CLOSE_EDIT_ASSIGNMENT_DIALOG';

export const OPEN_NEW_LECTURE_DIALOG = 'app/LMS/OPEN_NEW_LECTURE_DIALOG';
export const CLOSE_NEW_LECTURE_DIALOG = 'app/LMS/CLOSE_NEW_LECTURE_DIALOG';

export const OPEN_EDIT_LECTURE_DIALOG = 'app/LMS/OPEN_EDIT_LECTURE_DIALOG';
export const CLOSE_EDIT_LECTURE_DIALOG = 'app/LMS/CLOSE_EDIT_LECTURE_DIALOG';

export const OPEN_NEW_COURSE_DIALOG = 'app/LMS/OPEN_NEW_COURSE_DIALOG';
export const CLOSE_NEW_COURSE_DIALOG = 'app/LMS/CLOSE_NEW_COURSE_DIALOG';

export const OPEN_EDIT_COURSE_DIALOG = 'app/LMS/OPEN_EDIT_COURSE_DIALOG';
export const CLOSE_EDIT_COURSE_DIALOG = 'app/LMS/CLOSE_EDIT_COURSE_DIALOG';

export const GET_ASSIGNMENTS = 'app/LMS/GET_ASSIGNMENTS';
export const GET_ASSIGNMENTS_SUCCESS = 'app/LMS/GET_ASSIGNMENTS_SUCCESS';
export const GET_ASSIGNMENTS_ERROR = 'app/LMS/GET_ASSIGNMENTS_ERROR';

export const CREATE_ASSIGNMENT = 'app/LMS/CREATE_ASSIGNMENT';
export const CREATE_ASSIGNMENT_SUCCESS = 'app/LMS/CREATE_ASSIGNMENT_SUCCESS';
export const CREATE_ASSIGNMENT_ERROR = 'app/LMS/CREATE_ASSIGNMENT_ERROR';

export const UPDATE_ASSIGNMENT = 'app/LMS/UPDATE_ASSIGNMENT';
export const UPDATE_ASSIGNMENT_SUCCESS = 'app/LMS/UPDATE_ASSIGNMENT_SUCCESS';
export const UPDATE_ASSIGNMENT_ERROR = 'app/LMS/UPDATE_ASSIGNMENT_ERROR';

export const GET_LECTURES = 'app/LMS/GET_LECTURES';
export const GET_LECTURES_SUCCESS = 'app/LMS/GET_LECTURES_SUCCESS';
export const GET_LECTURES_ERROR = 'app/LMS/GET_LECTURES_ERROR';

export const CREATE_LECTURE = 'app/LMS/CREATE_LECTURE';
export const CREATE_LECTURE_SUCCESS = 'app/LMS/CREATE_LECTURE_SUCCESS';
export const CREATE_LECTURE_ERROR = 'app/LMS/CREATE_LECTURE_ERROR';

export const UPDATE_LECTURE = 'app/LMS/UPDATE_LECTURE';
export const UPDATE_LECTURE_SUCCESS = 'app/LMS/UPDATE_LECTURE_SUCCESS';
export const UPDATE_LECTURE_ERROR = 'app/LMS/UPDATE_LECTURE_ERROR';

export const GET_COURSES = 'app/LMS/GET_COURSES';
export const GET_COURSES_SUCCESS = 'app/LMS/GET_COURSES_SUCCESS';
export const GET_COURSES_ERROR = 'app/LMS/GET_COURSES_ERROR';

export const CREATE_COURSE = 'app/LMS/CREATE_COURSE';
export const CREATE_COURSE_SUCCESS = 'app/LMS/CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_ERROR = 'app/LMS/CREATE_COURSE_ERROR';

export const UPDATE_COURSE = 'app/LMS/UPDATE_COURSE';
export const UPDATE_COURSE_SUCCESS = 'app/LMS/UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_ERROR = 'app/LMS/UPDATE_COURSE_ERROR';
