/*
 *
 * Accounting constants
 *
 */

export const DEFAULT_ACTION = 'app/Accounting/DEFAULT_ACTION';

export const OPEN_NEW_ACCOUNT_DIALOG = 'app/Accounting/OPEN_NEW_ACCOUNT_DIALOG';
export const CLOSE_NEW_ACCOUNT_DIALOG = 'app/Accounting/CLOSE_NEW_ACCOUNT_DIALOG';

export const EDIT_OPEN_ACCOUNT_DIALOG = 'app/Accounting/EDIT_OPEN_ACCOUNT_DIALOG';
export const EDIT_CLOSE_ACCOUNT_DIALOG = 'app/Accounting/EDIT_CLOSE_ACCOUNT_DIALOG';

export const GET_ALL_ACCOUNT_TYPES = 'app/Accounting/GET_ALL_ACCOUNT_TYPES';
export const GET_ALL_ACCOUNT_TYPES_SUCCESS = 'app/Accounting/GET_ALL_ACCOUNT_TYPES_SUCCESS';
export const GET_ALL_ACCOUNT_TYPES_ERR = 'app/Accounting/GET_ALL_ACCOUNT_TYPES_ERR';

export const GET_DETAIL_TYPES = 'app/Accounting/GET_DETAIL_TYPES';
export const GET_DETAIL_TYPES_SUCCESS = 'app/Accounting/GET_DETAIL_TYPES_SUCCESS';
export const GET_DETAIL_TYPES_ERR = 'app/Accounting/GET_DETAIL_TYPES_ERR';

export const CREATE_NEW_CHART_OF_ACCOUNT = 'app/Accounting/CREATE_NEW_CHART_OF_ACCOUNT';
export const CREATE_NEW_CHART_OF_ACCOUNT_SUCCESS = 'app/Accounting/CREATE_NEW_CHART_OF_ACCOUNT_SUCCESS';
export const CREATE_NEW_CHART_OF_ACCOUNT_ERR = 'app/Accounting/CREATE_NEW_CHART_OF_ACCOUNT_ERR';

export const GET_ALL_CHART_OF_ACCOUNT = 'app/Accounting/GET_ALL_CHART_OF_ACCOUNT';
export const GET_ALL_CHART_OF_ACCOUNT_SUCCESS = 'app/Accounting/GET_ALL_CHART_OF_ACCOUNT_SUCCESS';
export const GET_ALL_CHART_OF_ACCOUNT_ERR = 'app/Accounting/GET_ALL_CHART_OF_ACCOUNT_ERR';

export const UPDATE_CHART_OF_ACCOUNT = 'app/Accounting/UPDATE_CHART_OF_ACCOUNT';
export const UPDATE_CHART_OF_ACCOUNT_SUCCESS = 'app/Accounting/UPDATE_CHART_OF_ACCOUNT_SUCCESS';
export const UPDATE_CHART_OF_ACCOUNT_ERR = 'app/Accounting/UPDATE_CHART_OF_ACCOUNT_ERR';

export const DELETE_CHART_OF_ACCOUNT = 'app/Accounting/DELETE_CHART_OF_ACCOUNT';
export const DELETE_CHART_OF_ACCOUNT_SUCCESS = 'app/Accounting/DELETE_CHART_OF_ACCOUNT_SUCCESS';
export const DELETE_CHART_OF_ACCOUNT_ERR = 'app/Accounting/DELETE_CHART_OF_ACCOUNT_ERR';