/*
 *
 * Crm constants
 *
 */

export const OPEN_SCHEDULE_REMINDER_DIALOG = 'app/Crm/OPEN_SCHEDULE_REMINDER_DIALOG';
export const CLOSE_SCHEDULE_REMINDER_DIALOG = 'app/Crm/CLOSE_SCHEDULE_REMINDER_DIALOG';

export const GET_EMPLOYEES = 'app/Crm/GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'app/Crm/GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'app/Crm/GET_EMPLOYEES_ERROR';

export const GET_CONTACTS = 'app/Crm/GET_CONTACTS';
export const GET_CONTACTS_SUCCESS = 'app/Crm/GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_ERROR = 'app/Crm/GET_CONTACTS_ERROR';

export const GET_COMPANIES = 'app/Crm/GET_ALL_COMPANIES';
export const GET_COMPANIES_SUCCESS = 'app/Crm/GET_ALL_COMPANIES_SUCCESS';
export const GET_COMPANIES_ERROR = 'app/Crm/GET_ALL_COMPANIES_ERROR';

export const GET_SCHEDULES = 'app/Crm/GET_SCHEDULES';
export const GET_SCHEDULES_SUCCESS = 'app/Crm/GET_SCHEDULES_SUCCESS';
export const GET_SCHEDULES_ERROR = 'app/Crm/GET_SCHEDULES_ERROR';

export const GET_TASKS = 'app/Crm/GET_TASKS';
export const GET_TASKS_SUCCESS = 'app/Crm/GET_TASKS_SUCCESS';
export const GET_TASKS_ERROR = 'app/Crm/GET_TASKS_ERROR';
