/*
 *
 * Crm constants
 *
 */

export const OPEN_NEW_SCHEDULE_DIALOG = 'app/Crm/OPEN_NEW_SCHEDULE_DIALOG';
export const CLOSE_NEW_SCHEDULE_DIALOG = 'app/Crm/CLOSE_NEW_SCHEDULE_DIALOG';

export const OPEN_NEW_PARTICIPANT_DIALOG = 'app/Crm/OPEN_NEW_PARTICIPANT_DIALOG';
export const CLOSE_NEW_PARTICIPANT_DIALOG = 'app/Crm/CLOSE_NEW_PARTICIPANT_DIALOG';
