export const LOGIN = 'app/App/LOGIN';
export const LOGIN_SUCCESS = 'app/App/LOGIN_SUCCESS';
export const LOGIN_ERROR = 'app/App/LOGIN_ERROR';

export const GET_USER_PROFILE = 'app/App/GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'app/App/GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_ERROR = 'app/App/GET_USER_PROFILE_ERROR';

export const OPEN_SNACKBAR = 'app/App/OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'app/App/CLOSE_SNACKBAR';

export const LOG_OUT = 'app/App/LOG_OUT';

export const POST_FCM_TOKEN = 'app/App/POST_FCM_TOKEN';
export const POST_FCM_TOKEN_SUCCESS = 'app/App/POST_FCM_TOKEN_SUCCESS';
export const POST_FCM_TOKEN_ERROR = 'app/App/POST_FCM_TOKEN_ERROR';

export const CHECK_ACTIVE_SESSION = 'app/App/CHECK_ACTIVE_SESSION';
export const CHECK_ACTIVE_SESSION_SUCCESS = 'app/App/CHECK_ACTIVE_SESSION_SUCCESS';
export const CHECK_ACTIVE_SESSION_ERROR = 'app/App/CHECK_ACTIVE_SESSION_ERROR';

export const REFRESH_TOKEN = 'app/App/REFRESH_TOKEN';
export const REFRESH_TOKEN_SUCCESS = 'app/App/REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_ERROR = 'app/App/REFRESH_TOKEN_ERROR';
