/*
 *
 * LMS Course Category constants
 *
 */

export const OPEN_NEW_CATEGORY_DIALOG = 'app/LMS/OPEN_NEW_CATEGORY_DIALOG';
export const CLOSE_NEW_CATEGORY_DIALOG = 'app/LMS/CLOSE_NEW_CATEGORY_DIALOG';

export const OPEN_EDIT_CATEGORY_DIALOG = 'app/LMS/OPEN_EDIT_CATEGORY_DIALOG';
export const CLOSE_EDIT_CATEGORY_DIALOG = 'app/LMS/CLOSE_EDIT_CATEGORY_DIALOG';

export const GET_CATEGORIES = 'app/LMS/GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'app/LMS/GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'app/LMS/GET_CATEGORIES_ERROR';

export const CREATE_CATEGORY = 'app/LMS/CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'app/LMS/CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_ERROR = 'app/LMS/CREATE_CATEGORY_ERROR';

export const UPDATE_CATEGORY = 'app/LMS/UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'app/LMS/UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_ERROR = 'app/LMS/UPDATE_CATEGORY_ERROR';

export const DELETE_CATEGORY = 'app/LMS/DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'app/LMS/DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'app/LMS/DELETE_CATEGORY_ERROR';