/*
 *
 * Journal constants
 *
 */

export const DEFAULT_ACTION = 'app/Journal/DEFAULT_ACTION';

export const OPEN_NEW_JOURNAL_DIALOG = 'app/Settings/OPEN_NEW_JOURNAL_DIALOG';
export const CLOSE_NEW_JOURNAL_DIALOG = 'app/Settings/CLOSE_NEW_JOURNAL_DIALOG';

export const OPEN_EDIT_JOURNAL_DIALOG = 'app/Settings/OPEN_EDIT_JOURNAL_DIALOG';
export const CLOSE_EDIT_JOURNAL_DIALOG =
  'app/Settings/CLOSE_EDIT_JOURNAL_DIALOG';

export const GET_ALL_CHART_OF_ACCOUNT = 'app/Journal/GET_ALL_CHART_OF_ACCOUNT';
export const GET_ALL_CHART_OF_ACCOUNT_SUCCESS =
  'app/Journal/GET_ALL_CHART_OF_ACCOUNT_SUCCESS';
export const GET_ALL_CHART_OF_ACCOUNT_ERR =
  'app/Journal/GET_ALL_CHART_OF_ACCOUNT_ERR';

export const GET_ACCOUNT_PERIOD = 'app/Journal/GET_ACCOUNT_PERIOD';
export const GET_ACCOUNT_PERIOD_SUCCESS =
  'app/Journal/GET_ACCOUNT_PERIOD_SUCCESS';
export const GET_ACCOUNT_PERIOD_ERR = 'app/Journal/GET_ACCOUNT_PERIOD_ERR';

export const GET_CURRENCIES = 'app/Settings/GET_CURRENCIES';
export const GET_CURRENCIES_SUCCESS = 'app/Settings/GET_CURRENCIES_SUCCESS';
export const GET_CURRENCIES_ERROR = 'app/Settings/GET_CURRENCIES_ERROR';

export const CREATE_NEW_ACCOUNT_JOURNAL =
  'app/Journal/CREATE_NEW_ACCOUNT_JOURNAL';
export const CREATE_NEW_ACCOUNT_JOURNAL_SUCCESS =
  'app/Journal/CREATE_NEW_ACCOUNT_JOURNAL_SUCCESS';
export const CREATE_NEW_ACCOUNT_JOURNAL_ERR =
  'app/Journal/CREATE_NEW_ACCOUNT_JOURNAL_ERR';

export const GET_JOURNAL_LIST = 'app/Journal/GET_JOURNAL_LIST';
export const GET_JOURNAL_LIST_SUCCESS = 'app/Journal/GET_JOURNAL_LIST_SUCCESS';
export const GET_JOURNAL_LIST_ERR = 'app/Journal/GET_JOURNAL_LIST_ERR';
