/*
 *
 * Journal constants
 *
 */

export const DEFAULT_ACTION = 'app/Journal/DEFAULT_ACTION';


export const GET_ALL_CHART_OF_ACCOUNT = 'app/Journal/GET_ALL_CHART_OF_ACCOUNT';
export const GET_ALL_CHART_OF_ACCOUNT_SUCCESS = 'app/Journal/GET_ALL_CHART_OF_ACCOUNT_SUCCESS';
export const GET_ALL_CHART_OF_ACCOUNT_ERR = 'app/Journal/GET_ALL_CHART_OF_ACCOUNT_ERR';

export const GET_ACCOUNT_PERIOD = 'app/Journal/GET_ACCOUNT_PERIOD';
export const GET_ACCOUNT_PERIOD_SUCCESS = 'app/Journal/GET_ACCOUNT_PERIOD_SUCCESS';
export const GET_ACCOUNT_PERIOD_ERR = 'app/Journal/GET_ACCOUNT_PERIOD_ERR';

export const CREATE_NEW_ACCOUNT_JOURNAL = 'app/Journal/CREATE_NEW_ACCOUNT_JOURNAL';
export const CREATE_NEW_ACCOUNT_JOURNAL_SUCCESS = 'app/Journal/CREATE_NEW_ACCOUNT_JOURNAL_SUCCESS';
export const CREATE_NEW_ACCOUNT_JOURNAL_ERR = 'app/Journal/CREATE_NEW_ACCOUNT_JOURNAL_ERR';
