/*
 *
 * Crm constants
 *
 */

export const OPEN_NEW_ACTIVITIES_DIALOG = 'app/Crm/OPEN_NEW_ACTIVITIES_DIALOG';
export const CLOSE_NEW_ACTIVITIES_DIALOG = 'app/Crm/CLOSE_NEW_ACTIVITIES_DIALOG';

export const GET_ALL_CRM_ACTIVITIES = 'app/Crm/GET_ALL_CRM_ACTIVITIES';
export const GET_ALL_CRM_ACTIVITIES_SUCCESS = 'app/Crm/GET_ALL_CRM_ACTIVITIES_SUCCESS';
export const GET_ALL_CRM_ACTIVITIES_ERROR = 'app/Crm/GET_ALL_CRM_ACTIVITIES_ERROR';

export const CREATE_CRM_ACTIVITY = 'app/Crm/CREATE_CRM_ACTIVITY';
export const CREATE_CRM_ACTIVITY_SUCCESS = 'app/Crm/CREATE_CRM_ACTIVITY_SUCCESS';
export const CREATE_CRM_ACTIVITY_ERROR = 'app/Crm/CREATE_CRM_ACTIVITY_ERROR';
