/*
 *
 * Crm constants
 *
 */

export const OPEN_NEW_CONTACT_DIALOG = 'app/Crm/OPEN_NEW_CONTACT_DIALOG';
export const CLOSE_NEW_CONTACT_DIALOG = 'app/Crm/CLOSE_NEW_CONTACT_DIALOG';

export const OPEN_NEW_CONTACT_DETAILS_DIALOG = 'app/Crm/OPEN_NEW_CONTACT_DETAILS_DIALOG';
export const CLOSE_NEW_CONTACT_DETAILS_DIALOG = 'app/Crm/CLOSE_NEW_CONTACT_DETAILS_DIALOG';
